"""
Auto-ported glasses catalog from Altis's original ToonDNA.GlassesStyles.
This file is generated -- see the porting session notes for how it was produced.
"""
from __future__ import annotations
from toontown.toon.accessories.AltisLegacyAccessories import AltisLegacyGlassesItemDefinition
from toontown.inventory.enums.ItemEnums import GlassesItemType

AltisLegacyGlassesRegistry = {
    GlassesItemType.Altis_2019_glasses: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_msk_2019_glasses', name='Glasses Style 2019_glasses'),
    GlassesItemType.Altis_2020_glasses: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/2020_glasses', name='Glasses Style 2020_glasses'),
    GlassesItemType.Altis_2022_glasses: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/2022_glasses', name='Glasses Style 2022_glasses'),
    GlassesItemType.Altis_brovinci_glasses: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/social/bro/brovinci_glasses', name='Glasses Style brovinci_glasses'),
    GlassesItemType.Altis_chair_glasses: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/social/discord/cc_m_acc_gl_promo_chairman', texturePath='phase_4/maps/social/discord/cc_t_acc_gl_promo_chairman.png', name='Glasses Style chair_glasses'),
    GlassesItemType.Altis_cookie_glasses: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_cookieglasses', name='Glasses Style cookie_glasses'),
    GlassesItemType.Altis_count_mask: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_countmask', name='Glasses Style count_mask'),
    GlassesItemType.Altis_ddl_sleepingmask: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_sleepingmask', name='Glasses Style ddl_sleepingmask'),
    GlassesItemType.Altis_eye_spring: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/apriltoons/tt_m_chr_avt_acc_msk_eye_spring', name='Glasses Style eye_spring'),
    GlassesItemType.Altis_flight_goggles: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/apriltoons/tt_m_chr_avt_acc_msk_flight_goggles', name='Glasses Style flight_goggles'),
    GlassesItemType.Altis_flunky_glasses: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/apriltoons/tt_m_chr_avt_acc_msk_flunky_glasses', name='Glasses Style flunky_glasses'),
    GlassesItemType.Altis_g3d1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_squareRims', name='Movie Glasses'),
    GlassesItemType.Altis_gag1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_alienGlasses', name='Alien Eyes by Alexandra'),
    GlassesItemType.Altis_gav1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_3dGlasses', name='Aviator'),
    GlassesItemType.Altis_gce1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_aviator', name='Cateye Glasses'),
    GlassesItemType.Altis_gdk1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_catEyeGlasses', name='Nerd Glasses'),
    GlassesItemType.Altis_ggl1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_scubaMask', name='Goggles'),
    GlassesItemType.Altis_ggm1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_goggles', name='Groucho Glasses'),
    GlassesItemType.Altis_ghg1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_grouchoMarxEyebrow', name='Heart Glasses'),
    GlassesItemType.Altis_ghw1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_eyepatch', name='Skull Eyepatch'),
    GlassesItemType.Altis_ghw2: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_eyepatch', texturePath='phase_4/maps/tt_t_chr_avt_acc_msk_eyepatchGems.png', name='Gem Eyepatch'),
    GlassesItemType.Altis_ghw3: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_eyepatch', texturePath='phase_4/maps/tt_t_chr_avt_acc_msk_eyepatchSkull.png', name='Limey\'s Eyepatch'),
    GlassesItemType.Altis_gie1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_heartGlasses', name='Bug Eye Glasses'),
    GlassesItemType.Altis_gift_glasses: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/giftglasses', name='Glasses Style gift_glasses'),
    GlassesItemType.Altis_gift_glasses_blue: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/giftglasses', texturePath='phase_4/maps/winter/gift_glasses/giftglasses_blue.png', name='Glasses Style gift_glasses_blue'),
    GlassesItemType.Altis_gift_glasses_cyan: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/giftglasses', texturePath='phase_4/maps/winter/gift_glasses/giftglasses_cyan.png', name='Glasses Style gift_glasses_cyan'),
    GlassesItemType.Altis_gift_glasses_green: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/giftglasses', texturePath='phase_4/maps/winter/gift_glasses/giftglasses_green.png', name='Glasses Style gift_glasses_green'),
    GlassesItemType.Altis_gift_glasses_orange: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/giftglasses', texturePath='phase_4/maps/winter/gift_glasses/giftglasses_orange.png', name='Glasses Style gift_glasses_orange'),
    GlassesItemType.Altis_gift_glasses_pink: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/giftglasses', texturePath='phase_4/maps/winter/gift_glasses/giftglasses_pink.png', name='Glasses Style gift_glasses_pink'),
    GlassesItemType.Altis_gift_glasses_purple: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/giftglasses', texturePath='phase_4/maps/winter/gift_glasses/giftglasses_purple.png', name='Glasses Style gift_glasses_purple'),
    GlassesItemType.Altis_gift_glasses_red: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/giftglasses', texturePath='phase_4/maps/winter/gift_glasses/giftglasses_red.png', name='Glasses Style gift_glasses_red'),
    GlassesItemType.Altis_gift_glasses_yellow: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/giftglasses', texturePath='phase_4/maps/winter/gift_glasses/giftglasses_yellow.png', name='Glasses Style gift_glasses_yellow'),
    GlassesItemType.Altis_gjo1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_dorkGlasses', name='Celebrity Shades'),
    GlassesItemType.Altis_glasses_cardBlack: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_cardGlassesBlack', name='Glasses Style glasses_cardBlack'),
    GlassesItemType.Altis_glasses_cardRed: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_cardGlassesRed', name='Glasses Style glasses_cardRed'),
    GlassesItemType.Altis_glasses_cyberpunk: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/social/cyberpunk/cc_m_acc_msk_cyberpunk', name='Glasses Style glasses_cyberpunk'),
    GlassesItemType.Altis_glasses_funky: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_funkyglasses', name='Glasses Style glasses_funky'),
    GlassesItemType.Altis_glasses_goggles_spy: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/cc_m_acc_face_gl_goggles_spy', name='Glasses Style glasses_goggles_spy'),
    GlassesItemType.Altis_glasses_low_baller: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/apriltoons/cc_m_acc_msk_low_baller', name='Glasses Style glasses_low_baller'),
    GlassesItemType.Altis_glasses_mouthpiece: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/bosses/glasses_mouthpiece', name='Glasses Style glasses_mouthpiece'),
    GlassesItemType.Altis_glasses_pacesetter: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/bosses/glasses_pacesetter', name='Glasses Style glasses_pacesetter'),
    GlassesItemType.Altis_glasses_pirate_mask: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/cc_m_acc_face_msk_pirate_ghost', name='Glasses Style glasses_pirate_mask'),
    GlassesItemType.Altis_gmb1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_miniblinds', name='White Mini Blinds'),
    GlassesItemType.Altis_gmn1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_masqueradeTypeMask3', name='Monocle'),
    GlassesItemType.Altis_gmo1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_monocle', name='Smooch Glasses'),
    GlassesItemType.Altis_gmt1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_insectEyeGlasses', name='Black Secret ID Mask'),
    GlassesItemType.Altis_gmt2: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_insectEyeGlasses', texturePath='phase_4/maps/tt_t_chr_avt_acc_msk_masqueradeTypeMask2.png', name='Blue Secret ID Mask'),
    GlassesItemType.Altis_gmt3: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_masqueradeTypeMask', name='Blue Carnivale Mask'),
    GlassesItemType.Altis_gmt4: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_masqueradeTypeMask', texturePath='phase_4/maps/tt_t_chr_avt_acc_msk_masqueradeTypeMask4.png', name='Purple Carnivale Mask'),
    GlassesItemType.Altis_gmt5: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_masqueradeTypeMask', texturePath='phase_4/maps/tt_t_chr_avt_acc_msk_masqueradeTypeMask5.png', name='Aqua Carnivale Mask'),
    GlassesItemType.Altis_gnr1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_narrowGlasses', name='Purple Narrow Glasses'),
    GlassesItemType.Altis_grd1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_roundGlasses', name='Round Glasses'),
    GlassesItemType.Altis_gsb1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_jackieOShades', name='Scuba Mask'),
    GlassesItemType.Altis_gsr1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_mouthGlasses', name='Square Frame Glasses'),
    GlassesItemType.Altis_gst1: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_msk_starGlasses', name='Yellow Star Glasses'),
    GlassesItemType.Altis_hwtown_mask: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_t_chr_avt_acc_hat_hwtown_mask', name='Glasses Style hwtown_mask'),
    GlassesItemType.Altis_hypno: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_hypno', name='Glasses Style hypno'),
    GlassesItemType.Altis_hypno_2019: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_hypno', texturePath='phase_4/maps/halloween/accessories_textures/tt_t_chr_avt_acc_hallowen_hypno_2019.png', name='Glasses Style hypno_2019'),
    GlassesItemType.Altis_hypno_blue: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_hypno', texturePath='phase_13/maps/events/halloween/hypno_blue.png', name='Glasses Style hypno_blue'),
    GlassesItemType.Altis_hypno_darkpurple: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_hypno', texturePath='phase_13/maps/events/halloween/hypno_darkpurple.png', name='Glasses Style hypno_darkpurple'),
    GlassesItemType.Altis_hypno_lightblue: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_hypno', texturePath='phase_13/maps/events/halloween/hypno_lightblue.png', name='Glasses Style hypno_lightblue'),
    GlassesItemType.Altis_hypno_orange: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_hypno', texturePath='phase_13/maps/events/halloween/hypno_orange.png', name='Glasses Style hypno_orange'),
    GlassesItemType.Altis_hypno_pink: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_hypno', texturePath='phase_13/maps/events/halloween/hypno_pink.png', name='Glasses Style hypno_pink'),
    GlassesItemType.Altis_hypno_purple: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_hypno', texturePath='phase_13/maps/events/halloween/hypno_purple.png', name='Glasses Style hypno_purple'),
    GlassesItemType.Altis_hypno_rainbow: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_hypno', texturePath='phase_13/maps/events/halloween/hypno_rainbow.png', name='Glasses Style hypno_rainbow'),
    GlassesItemType.Altis_hypno_yellow: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_hypno', texturePath='phase_13/maps/events/halloween/hypno_yellow.png', name='Glasses Style hypno_yellow'),
    GlassesItemType.Altis_muzzle_rose: AltisLegacyGlassesItemDefinition(modelPath='phase_6/models/miniboss/majorplayer_rose', name='Glasses Style muzzle_rose'),
    GlassesItemType.Altis_orn_glasses_black: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/ornament_glasses', texturePath='phase_4/maps/winter/ornament_glasses/orn_glasses_black.png', name='Glasses Style orn_glasses_black'),
    GlassesItemType.Altis_orn_glasses_blue: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/ornament_glasses', texturePath='phase_4/maps/winter/ornament_glasses/orn_glasses_blue.png', name='Glasses Style orn_glasses_blue'),
    GlassesItemType.Altis_orn_glasses_cyan: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/ornament_glasses', texturePath='phase_4/maps/winter/ornament_glasses/orn_glasses_cyan.png', name='Glasses Style orn_glasses_cyan'),
    GlassesItemType.Altis_orn_glasses_green: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/ornament_glasses', texturePath='phase_4/maps/winter/ornament_glasses/orn_glasses_green.png', name='Glasses Style orn_glasses_green'),
    GlassesItemType.Altis_orn_glasses_orange: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/ornament_glasses', texturePath='phase_4/maps/winter/ornament_glasses/orn_glasses_orange.png', name='Glasses Style orn_glasses_orange'),
    GlassesItemType.Altis_orn_glasses_pink: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/ornament_glasses', texturePath='phase_4/maps/winter/ornament_glasses/orn_glasses_pink.png', name='Glasses Style orn_glasses_pink'),
    GlassesItemType.Altis_orn_glasses_purple: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/ornament_glasses', texturePath='phase_4/maps/winter/ornament_glasses/orn_glasses_purple.png', name='Glasses Style orn_glasses_purple'),
    GlassesItemType.Altis_orn_glasses_rainbow: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/ornament_glasses', texturePath='phase_4/maps/winter/ornament_glasses/orn_glasses_rainbow.png', name='Glasses Style orn_glasses_rainbow'),
    GlassesItemType.Altis_orn_glasses_red: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/ornament_glasses', texturePath='phase_4/maps/winter/ornament_glasses/orn_glasses_red.png', name='Glasses Style orn_glasses_red'),
    GlassesItemType.Altis_orn_glasses_white: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/ornament_glasses', texturePath='phase_4/maps/winter/ornament_glasses/orn_glasses_white.png', name='Glasses Style orn_glasses_white'),
    GlassesItemType.Altis_orn_glasses_yellow: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/ornament_glasses', texturePath='phase_4/maps/winter/ornament_glasses/orn_glasses_yellow.png', name='Glasses Style orn_glasses_yellow'),
    GlassesItemType.Altis_outback_sunnyglasses: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/outback/sunnyglasses', name='Glasses Style outback_sunnyglasses'),
    GlassesItemType.Altis_painter_brush: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_painter_paintbrush', name='Glasses Style painter_brush'),
    GlassesItemType.Altis_scifi_visor: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/apriltoons/scifi_visor', name='Glasses Style scifi_visor'),
    GlassesItemType.Altis_seven_glasses: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_hypno', texturePath='phase_13/maps/events/btl/accessories/seven_hypno.png', name='Glasses Style seven_glasses'),
    GlassesItemType.Altis_snow_goggles_blue: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_msk_snow_goggles_blue', name='Glasses Style snow_goggles_blue'),
    GlassesItemType.Altis_snow_goggles_green: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_msk_snow_goggles_green', name='Glasses Style snow_goggles_green'),
    GlassesItemType.Altis_snow_goggles_grey: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_msk_snow_goggles_grey', name='Glasses Style snow_goggles_grey'),
    GlassesItemType.Altis_snow_goggles_pink: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_msk_snow_goggles_pink', name='Glasses Style snow_goggles_pink'),
    GlassesItemType.Altis_snow_goggles_rainbow: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_msk_snow_goggles_rainbow', name='Glasses Style snow_goggles_rainbow'),
    GlassesItemType.Altis_snow_goggles_red: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_msk_snow_goggles_red', name='Glasses Style snow_goggles_red'),
    GlassesItemType.Altis_snow_goggles_vintage: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_msk_snow_goggles_vintage', name='Glasses Style snow_goggles_vintage'),
    GlassesItemType.Altis_spider_glasses: AltisLegacyGlassesItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_msk_spiderglasses', name='Glasses Style spider_glasses'),
    GlassesItemType.Altis_vinny_stache: AltisLegacyGlassesItemDefinition(modelPath='phase_13/models/events/btl/accessories/mustache', texturePath='phase_13/maps/events/btl/accessories/mustache.png', name='Glasses Style vinny_stache'),
    GlassesItemType.Altis_x_glasses_b: AltisLegacyGlassesItemDefinition(modelPath='phase_13/models/events/btl/accessories/x_glasses', texturePath='phase_13/maps/events/btl/accessories/x_glasses.png', name='Glasses Style x_glasses_b'),
    GlassesItemType.Altis_x_glasses_go: AltisLegacyGlassesItemDefinition(modelPath='phase_13/models/events/btl/accessories/x_glasses', texturePath='phase_13/maps/events/btl/accessories/x_glasses_GOLD.png', name='Glasses Style x_glasses_go'),
    GlassesItemType.Altis_x_glasses_gr: AltisLegacyGlassesItemDefinition(modelPath='phase_13/models/events/btl/accessories/x_glasses', texturePath='phase_13/maps/events/btl/accessories/x_glasses_GREEN.png', name='Glasses Style x_glasses_gr'),
    GlassesItemType.Altis_x_glasses_ra: AltisLegacyGlassesItemDefinition(modelPath='phase_13/models/events/btl/accessories/x_glasses', texturePath='phase_13/maps/events/btl/accessories/x_glasses_RAINBOW.png', name='Glasses Style x_glasses_ra'),
    GlassesItemType.Altis_x_glasses_red: AltisLegacyGlassesItemDefinition(modelPath='phase_13/models/events/btl/accessories/x_glasses', texturePath='phase_13/maps/events/btl/accessories/x_glasses_RED.png', name='Glasses Style x_glasses_red'),
}
