"""
Auto-ported hat catalog from Altis's original ToonDNA.HatStyles.
This file is generated -- see the porting session notes for how it was produced.
"""
from __future__ import annotations
from toontown.toon.accessories.AltisLegacyAccessories import AltisLegacyHatItemDefinition
from toontown.inventory.enums.ItemEnums import HatItemType

AltisLegacyHatRegistry = {
    HatItemType.Altis_alchemist_goggles: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_hat_alchemistgoggles', name='Hat Style alchemist_goggles'),
    HatItemType.Altis_alien_hat: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/alien_hat', name='Hat Style alien_hat'),
    HatItemType.Altis_angel_halo: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/angel_halo', name='Hat Style angel_halo'),
    HatItemType.Altis_angel_halo_blue: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/angel_halo', texturePath='phase_13/maps/events/btl/accessories/angel-demon-blue.png', name='Hat Style angel_halo_blue'),
    HatItemType.Altis_angel_halo_green: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/angel_halo', texturePath='phase_13/maps/events/btl/accessories/angel-demon-green.png', name='Hat Style angel_halo_green'),
    HatItemType.Altis_angel_halo_orange: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/angel_halo', texturePath='phase_13/maps/events/btl/accessories/angel-demon-orange.png', name='Hat Style angel_halo_orange'),
    HatItemType.Altis_angel_halo_purple: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/angel_halo', texturePath='phase_13/maps/events/btl/accessories/angel-demon-purple.png', name='Hat Style angel_halo_purple'),
    HatItemType.Altis_angel_halo_red: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/angel_halo', texturePath='phase_13/maps/events/btl/accessories/angel-demon-red.png', name='Hat Style angel_halo_red'),
    HatItemType.Altis_angel_halo_yellow: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/angel_halo', texturePath='phase_13/maps/events/btl/accessories/angel-demon-yellow.png', name='Hat Style angel_halo_yellow'),
    HatItemType.Altis_antlers: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_antlers', name='Hat Style antlers'),
    HatItemType.Altis_atticus_hat: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/atticushat', texturePath='phase_13/maps/events/btl/accessories/atticushat.png', name='Hat Style atticus_hat'),
    HatItemType.Altis_aviator_hat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/apriltoons/tt_m_chr_avt_acc_hat_aviatorcap', name='Hat Style aviator_hat'),
    HatItemType.Altis_bandana_deluxe: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_bandana2', name='Hat Style bandana-deluxe'),
    HatItemType.Altis_bat_bow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_hat_batbow', name='Hat Style bat_bow'),
    HatItemType.Altis_bobble_blue: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_bobblehat_blue', name='Hat Style bobble_blue'),
    HatItemType.Altis_bobble_green: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_bobblehat_green', name='Hat Style bobble_green'),
    HatItemType.Altis_bobble_grey: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_bobblehat_grey', name='Hat Style bobble_grey'),
    HatItemType.Altis_bobble_pink: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_bobblehat_pink', name='Hat Style bobble_pink'),
    HatItemType.Altis_bobble_rainbow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_bobblehat_rainbow', name='Hat Style bobble_rainbow'),
    HatItemType.Altis_bobble_red: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_bobblehat_red', name='Hat Style bobble_red'),
    HatItemType.Altis_bowling_ball: AltisLegacyHatItemDefinition(modelPath='phase_5/models/props/bowling_ball-mod', name='Hat Style bowling_ball'),
    HatItemType.Altis_brovinci_hair: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/bro/brovinci_hair', name='Hat Style brovinci_hair'),
    HatItemType.Altis_cake_hat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/anniversary/tt_m_chr_avt_acc_hat_cake', name='Hat Style cake_hat'),
    HatItemType.Altis_candle_hat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/past_candle', name='Hat Style candle_hat'),
    HatItemType.Altis_candycorn_bow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', texturePath='phase_13/maps/events/halloween/tt_t_chr_avt_acc_hat_ribbon_candyCorn.png', name='Hat Style candycorn_bow'),
    HatItemType.Altis_cauldron_hat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_hat_cauldronhat', name='Hat Style cauldron_hat'),
    HatItemType.Altis_clown_hat: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/apriltoons/clown_hat', name='Hat Style clown_hat'),
    HatItemType.Altis_cruller_beret: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_crullerberet', name='Hat Style cruller_beret'),
    HatItemType.Altis_demon_horns: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/demon_horns', name='Hat Style demon_horns'),
    HatItemType.Altis_demon_horns_blue: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/demon_horns', texturePath='phase_13/maps/events/btl/accessories/angel-demon-blue.png', name='Hat Style demon_horns_blue'),
    HatItemType.Altis_demon_horns_green: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/demon_horns', texturePath='phase_13/maps/events/btl/accessories/angel-demon-green.png', name='Hat Style demon_horns_green'),
    HatItemType.Altis_demon_horns_orange: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/demon_horns', texturePath='phase_13/maps/events/btl/accessories/angel-demon-orange.png', name='Hat Style demon_horns_orange'),
    HatItemType.Altis_demon_horns_purple: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/demon_horns', texturePath='phase_13/maps/events/btl/accessories/angel-demon-purple.png', name='Hat Style demon_horns_purple'),
    HatItemType.Altis_demon_horns_red: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/demon_horns', texturePath='phase_13/maps/events/btl/accessories/angel-demon-red.png', name='Hat Style demon_horns_red'),
    HatItemType.Altis_demon_horns_yellow: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/demon_horns', texturePath='phase_13/maps/events/btl/accessories/angel-demon-yellow.png', name='Hat Style demon_horns_yellow'),
    HatItemType.Altis_diploma: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/bosses/cc_m_acc_hat_diploma_bow', name='Hat Style diploma'),
    HatItemType.Altis_doe_beanie: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/doe/tt_m_chr_avt_acc_hat_doe_beanie', name='Hat Style doe_beanie'),
    HatItemType.Altis_donuthat_blue: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_donuthat', texturePath='phase_4/maps/social/gumball/ttcc_acc_donutblue.png', name='Hat Style donuthat_blue'),
    HatItemType.Altis_donuthat_chocolate: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_donuthat', texturePath='phase_4/maps/social/gumball/ttcc_acc_donutchocolate.png', name='Hat Style donuthat_chocolate'),
    HatItemType.Altis_donuthat_lemon: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_donuthat', texturePath='phase_4/maps/social/gumball/ttcc_acc_donutlemon.png', name='Hat Style donuthat_lemon'),
    HatItemType.Altis_donuthat_pink: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_donuthat', name='Hat Style donuthat_pink'),
    HatItemType.Altis_donuthat_vanilla: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_donuthat', texturePath='phase_4/maps/social/gumball/ttcc_acc_donutvanilla.png', name='Hat Style donuthat_vanilla'),
    HatItemType.Altis_easter_beanie: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/easter2020/easter_beanie', name='Hat Style easter_beanie'),
    HatItemType.Altis_electric_bolts: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_hat_electricbolts', name='Hat Style electric_bolts'),
    HatItemType.Altis_elf_green: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_elf_green', name='Hat Style elf_green'),
    HatItemType.Altis_elf_jolly_green: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/cc_m_acc_hat_elf', texturePath='phase_4/maps/winter/accessories_textures/cc_t_acc_hat_elf_whiteRed.png', name='Hat Style elf_jolly_green'),
    HatItemType.Altis_elf_red: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/cc_m_acc_hat_elf', name='Hat Style elf_red'),
    HatItemType.Altis_flowercrown_blue: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_blue.png', name='Hat Style flowercrown_blue'),
    HatItemType.Altis_flowercrown_cyan: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_cyan.png', name='Hat Style flowercrown_cyan'),
    HatItemType.Altis_flowercrown_cyanpurple: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_cyanpurple.png', name='Hat Style flowercrown_cyanpurple'),
    HatItemType.Altis_flowercrown_green: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_green.png', name='Hat Style flowercrown_green'),
    HatItemType.Altis_flowercrown_orange: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_orange.png', name='Hat Style flowercrown_orange'),
    HatItemType.Altis_flowercrown_orangepink: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_orangepink.png', name='Hat Style flowercrown_orangepink'),
    HatItemType.Altis_flowercrown_pink: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_pink.png', name='Hat Style flowercrown_pink'),
    HatItemType.Altis_flowercrown_pinkblue: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_pinkblue.png', name='Hat Style flowercrown_pinkblue'),
    HatItemType.Altis_flowercrown_purple: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_purple.png', name='Hat Style flowercrown_purple'),
    HatItemType.Altis_flowercrown_red: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_red.png', name='Hat Style flowercrown_red'),
    HatItemType.Altis_flowercrown_redyellow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_redyellow.png', name='Hat Style flowercrown_redyellow'),
    HatItemType.Altis_flowercrown_white: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', name='Hat Style flowercrown_white'),
    HatItemType.Altis_flowercrown_yellow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_flowercrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_flowercrown_yellow.png', name='Hat Style flowercrown_yellow'),
    HatItemType.Altis_frank_head: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_hat_frank_head', name='Hat Style frank_head'),
    HatItemType.Altis_fruit_pie: AltisLegacyHatItemDefinition(modelPath='phase_5/models/props/fruit-pie', name='Hat Style fruit_pie'),
    HatItemType.Altis_future_hood: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/future_hood', name='Hat Style future_hood'),
    HatItemType.Altis_gb_hairbow_black: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_black.png', name='Hat Style gb_hairbow_black'),
    HatItemType.Altis_gb_hairbow_blackwhite: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_blackwhite.png', name='Hat Style gb_hairbow_blackwhite'),
    HatItemType.Altis_gb_hairbow_blue: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_blue.png', name='Hat Style gb_hairbow_blue'),
    HatItemType.Altis_gb_hairbow_gray: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_gray.png', name='Hat Style gb_hairbow_gray'),
    HatItemType.Altis_gb_hairbow_green: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_green.png', name='Hat Style gb_hairbow_green'),
    HatItemType.Altis_gb_hairbow_orange: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_orange.png', name='Hat Style gb_hairbow_orange'),
    HatItemType.Altis_gb_hairbow_pink: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_pink.png', name='Hat Style gb_hairbow_pink'),
    HatItemType.Altis_gb_hairbow_pinkblack: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_pinkblack.png', name='Hat Style gb_hairbow_pinkblack'),
    HatItemType.Altis_gb_hairbow_polkadot: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_polkadot.png', name='Hat Style gb_hairbow_polkadot'),
    HatItemType.Altis_gb_hairbow_purple: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_purple.png', name='Hat Style gb_hairbow_purple'),
    HatItemType.Altis_gb_hairbow_purpleorange: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_purpleorange.png', name='Hat Style gb_hairbow_purpleorange'),
    HatItemType.Altis_gb_hairbow_red: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_red.png', name='Hat Style gb_hairbow_red'),
    HatItemType.Altis_gb_hairbow_yellow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_yellow.png', name='Hat Style gb_hairbow_yellow'),
    HatItemType.Altis_gb_hairbow_yellowblack: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/social/gumball/ttcc_acc_bowtie_yellowblack.png', name='Hat Style gb_hairbow_yellowblack'),
    HatItemType.Altis_grill: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/july4/grill', texturePath='phase_13/maps/events/july4/accessories/grill.png', name='Hat Style grill'),
    HatItemType.Altis_hat_number1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/apriltoons/hat-number1', name='Hat Style hat-number1'),
    HatItemType.Altis_hat1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_antenna', name='Antenna Thingy'),
    HatItemType.Altis_hat2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_spiderAntennaThingy', name='Spider Antenna Thingy'),
    HatItemType.Altis_hat_bananahat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_bananahat', name='Hat Style hat_bananahat'),
    HatItemType.Altis_hat_blackberet: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_blackberet', name='Hat Style hat_blackberet'),
    HatItemType.Altis_hat_butter: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_butter', name='Hat Style hat_butter'),
    HatItemType.Altis_hat_cardCrown: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_cardCrown', name='Hat Style hat_cardCrown'),
    HatItemType.Altis_hat_cardTopHat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_cardTopHat', name='Hat Style hat_cardTopHat'),
    HatItemType.Altis_hat_chainsaw: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/bosses/hat_chainsaw', name='Hat Style hat_chainsaw'),
    HatItemType.Altis_hat_clownbeanie: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_clownbeanie', name='Hat Style hat_clownbeanie'),
    HatItemType.Altis_hat_cog_bucket: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/apriltoons/cc_m_acc_hat_cog_bucket', name='Hat Style hat_cog_bucket'),
    HatItemType.Altis_hat_cyberpunk: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/cyberpunk/cc_m_acc_hat_cyberpunk', name='Hat Style hat_cyberpunk'),
    HatItemType.Altis_hat_engineer_cap: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_engineer_cap', name='Hat Style hat_engineer_cap'),
    HatItemType.Altis_hat_featherbedder: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/bosses/hat_unibrow', name='Hat Style hat_featherbedder'),
    HatItemType.Altis_hat_firestarter: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/bosses/hat_firestarter', name='Hat Style hat_firestarter'),
    HatItemType.Altis_hat_foreman: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/atticushat', texturePath='phase_4/maps/apriltoons/accessories/cc_t_acc_hat_foreman.png', name='Hat Style hat_foreman'),
    HatItemType.Altis_hat_goon_patrol_orange: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/apriltoons/cc_m_acc_hat_goon_patrol', texturePath='phase_4/maps/apriltoons/accessories/cc_t_acc_hat_goon_patrol_orange.png', name='Hat Style hat_goon_patrol_orange'),
    HatItemType.Altis_hat_goon_patrol_purple: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/apriltoons/cc_m_acc_hat_goon_patrol', texturePath='phase_4/maps/apriltoons/accessories/cc_t_acc_hat_goon_patrol_purple.png', name='Hat Style hat_goon_patrol_purple'),
    HatItemType.Altis_hat_goon_patrol_red: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/apriltoons/cc_m_acc_hat_goon_patrol', texturePath='phase_4/maps/apriltoons/accessories/cc_t_acc_hat_goon_patrol_red.png', name='Hat Style hat_goon_patrol_red'),
    HatItemType.Altis_hat_goon_patrol_yellow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/apriltoons/cc_m_acc_hat_goon_patrol', name='Hat Style hat_goon_patrol_yellow'),
    HatItemType.Altis_hat_goon_security: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/apriltoons/cc_m_acc_hat_goon_security', name='Hat Style hat_goon_security'),
    HatItemType.Altis_hat_gumball_hairbow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_hairbow', name='Hat Style hat_gumball_hairbow'),
    HatItemType.Altis_hat_gumball_hairbow_b: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_hairbow', texturePath='phase_4/maps/social/gumball/ttcc_acc_hairbow_B.png', name='Hat Style hat_gumball_hairbow_b'),
    HatItemType.Altis_hat_gumball_hairbow_br: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_hairbow', texturePath='phase_4/maps/social/gumball/ttcc_acc_hairbow_BR.png', name='Hat Style hat_gumball_hairbow_br'),
    HatItemType.Altis_hat_gumball_hairbow_g: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_hairbow', texturePath='phase_4/maps/social/gumball/ttcc_acc_hairbow_G.png', name='Hat Style hat_gumball_hairbow_g'),
    HatItemType.Altis_hat_gumball_hairbow_or: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_hairbow', texturePath='phase_4/maps/social/gumball/ttcc_acc_hairbow_OR.png', name='Hat Style hat_gumball_hairbow_or'),
    HatItemType.Altis_hat_gumball_hairbow_p: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_hairbow', texturePath='phase_4/maps/social/gumball/ttcc_acc_hairbow_P.png', name='Hat Style hat_gumball_hairbow_p'),
    HatItemType.Altis_hat_gumball_hairbow_pu: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_hairbow', texturePath='phase_4/maps/social/gumball/ttcc_acc_hairbow_PU.png', name='Hat Style hat_gumball_hairbow_pu'),
    HatItemType.Altis_hat_gumball_hairbow_rb: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_hairbow', texturePath='phase_4/maps/social/gumball/ttcc_acc_hairbow_RB.png', name='Hat Style hat_gumball_hairbow_rb'),
    HatItemType.Altis_hat_gumballhat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_gumballhat', name='Hat Style hat_gumballhat'),
    HatItemType.Altis_hat_high_roller: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/apriltoons/cc_m_acc_hat_high_roller', name='Hat Style hat_high_roller'),
    HatItemType.Altis_hat_icecube: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/bosses/hat_icecube', name='Hat Style hat_icecube'),
    HatItemType.Altis_hat_low_baller: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/apriltoons/cc_m_acc_hat_low_baller', name='Hat Style hat_low_baller'),
    HatItemType.Altis_hat_multislacker: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/bosses/hat_multislacker', name='Hat Style hat_multislacker'),
    HatItemType.Altis_hat_nightcap: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_nightcap', name='Hat Style hat_nightcap'),
    HatItemType.Altis_hat_pirate_ghost: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/cc_m_acc_hat_pirate_ghost', name='Hat Style hat_pirate_ghost'),
    HatItemType.Altis_hat_rainmaker_depression: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/bosses/hat_rainmaker', name='Hat Style hat_rainmaker_depression'),
    HatItemType.Altis_hat_smartcap: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/bosses/hat_smartcap', name='Hat Style hat_smartcap'),
    HatItemType.Altis_hat_treekiller: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/bosses/hat_treekiller', name='Hat Style hat_treekiller'),
    HatItemType.Altis_hat_wingsuit_helmet: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_wingsuit_helmet', name='Hat Style hat_wingsuit_helmet'),
    HatItemType.Altis_hat_witchhunter: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/bosses/hat_witchhunter', name='Hat Style hat_witchhunter'),
    HatItemType.Altis_hav1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_anvil', name='Anvil Hat'),
    HatItemType.Altis_hbb1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_baseball', name='Green Baseball Cap'),
    HatItemType.Altis_hbb2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_baseball', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_baseballBlue.png', name='Blue Baseball Cap'),
    HatItemType.Altis_hbb3: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_baseball', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_baseballOrange.png', name='Orange Baseball Cap'),
    HatItemType.Altis_hbb4: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_baseball', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_baseballYellow.png', name='Yellow Baseball Cap'),
    HatItemType.Altis_hbb5: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_baseball', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_baseballRed.png', name='Red Baseball Cap'),
    HatItemType.Altis_hbb6: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_baseball', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_baseballTeal.png', name='Aqua Baseball Cap'),
    HatItemType.Altis_hbb7: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_baseball', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_baseballPurple.png', name='Purple Baseball Cap'),
    HatItemType.Altis_hbn1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_birdNest', name='Bird Hat by Brianna'),
    HatItemType.Altis_hbw1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_bowler', name='Bowler Hat'),
    HatItemType.Altis_hby1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_bobbyHat', name='Bobby Hat'),
    HatItemType.Altis_hch1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_chefsHat', name='Chef Hat'),
    HatItemType.Altis_hcr1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_crown', name='Crown'),
    HatItemType.Altis_hcw1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_cowboyHat', name='Cowboy Hat'),
    HatItemType.Altis_hdt1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_detective', name='Detective Hat'),
    HatItemType.Altis_headset_spy: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/cc_m_acc_hat_headphones_spy', name='Hat Style headset_spy'),
    HatItemType.Altis_hfd1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_fedora', name='Fedora'),
    HatItemType.Altis_hfp1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_flowerPot', name='Flower Hat'),
    HatItemType.Altis_hfp2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_foilPyramid', name='Anti-Cog Control Hat'),
    HatItemType.Altis_hfr1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_carmenMirandaFruitHat', name='Samba Hat'),
    HatItemType.Altis_hfs1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_fishingHat', name='Fishing Hat'),
    HatItemType.Altis_hft1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_feathers', name='Fancy Feathers Hat'),
    HatItemType.Altis_hft2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_headband', name='Feather Headband'),
    HatItemType.Altis_hfz1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/bosses/hat_chainsaw', name='Fez Hat'),
    HatItemType.Altis_hgf1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_golfHat', name='Golf Hat'),
    HatItemType.Altis_hhd1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_beeHiveHairdo', name='Beehive Hairdo'),
    HatItemType.Altis_hhd2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_pompadorHairdo', name='Pompadour Hairdo'),
    HatItemType.Altis_hhm1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_romanHelmet', name='Roman Helmet'),
    HatItemType.Altis_hhm2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_vikingHelmet', name='Viking Helmet'),
    HatItemType.Altis_hhm3: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_conquistadorHelmet', name='Conquistador Helmet'),
    HatItemType.Altis_hhm4: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_firefighterHelmet', name='Firefighter Helmet'),
    HatItemType.Altis_hhm5: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_minersHardhatWithLight', name='Miner Hat'),
    HatItemType.Altis_hht1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_heart', name='Pink Heart'),
    HatItemType.Altis_hht2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_heart', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_heartYellow.png', name='Yellow Heart'),
    HatItemType.Altis_hhw1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_bandana', name='Bandana'),
    HatItemType.Altis_hhw2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_dinosaur', name='Toonosaur Hat'),
    HatItemType.Altis_hjh1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_jugheadHat', name='Jester Hat'),
    HatItemType.Altis_hmk1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_mickeysBandConductorHat', name='Mickey\'s Band Hat'),
    HatItemType.Altis_hnp1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_napoleonHat', name='Napoleon Hat'),
    HatItemType.Altis_hob1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_band', name='Jamboree Hat'),
    HatItemType.Altis_hpb1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_pillBox', name='Fancy Hat'),
    HatItemType.Altis_hpc1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_princess', name='Princess Hat'),
    HatItemType.Altis_hpc2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_pilotsCap', name='Pilot Cap'),
    HatItemType.Altis_hph1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_policeHat', name='Cop Hat'),
    HatItemType.Altis_hpp1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_propellerHat', name='Propeller Hat'),
    HatItemType.Altis_hpr1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_pirateHat', name='Pirate Hat'),
    HatItemType.Altis_hpt1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_partyHat', name='Party Hat'),
    HatItemType.Altis_hpt2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_partyHat', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_partyToon.png', name='Toon Party Hat'),
    HatItemType.Altis_hrb1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', name='Pink Bow'),
    HatItemType.Altis_hrb2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_ribbonRed.png', name='Red Bow'),
    HatItemType.Altis_hrb3: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_ribbonPurple.png', name='Purple Bow'),
    HatItemType.Altis_hrb4: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_ribbonYellow.png', name='Yellow Bow'),
    HatItemType.Altis_hrb5: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_ribbonChecker.png', name='Checker Bow'),
    HatItemType.Altis_hrb6: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_ribbonLtRed.png', name='Light Red Bow'),
    HatItemType.Altis_hrb7: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_ribbonRainbow.png', name='Rainbow Bow'),
    HatItemType.Altis_hrb8: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_ribbonPinkDots.png', name='Pink Dots Bow'),
    HatItemType.Altis_hrb9: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_ribbonCheckerGreen.png', name='Green Checker Bow'),
    HatItemType.Altis_hrh1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_robinHoodHat', name='Archer Hat'),
    HatItemType.Altis_hsb1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_sombreroHat', name='Sombrero Hat'),
    HatItemType.Altis_hsf1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_safari', name='Beige Safari Hat'),
    HatItemType.Altis_hsf2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_safari', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_safariBrown.png', name='Brown Safari Hat'),
    HatItemType.Altis_hsf3: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_safari', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_safariGreen.png', name='Green Safari Hat'),
    HatItemType.Altis_hsg1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_sandbag', name='Sandbag Hat'),
    HatItemType.Altis_hsl1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_sailorHat', name='Sailor Hat'),
    HatItemType.Altis_hst1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_strawHat', name='Straw Hat'),
    HatItemType.Altis_hsu1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_sunHat', name='Sun Hat'),
    HatItemType.Altis_htp1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_topHat', name='Black Top Hat'),
    HatItemType.Altis_htp2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_topHat', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_topHatBlue.png', name='Blue Top Hat'),
    HatItemType.Altis_htr1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_tiara', name='Tiara'),
    HatItemType.Altis_hw_gibus: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_hat_gibus', name='Hat Style hw_gibus'),
    HatItemType.Altis_hwg1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_rainbowAfroWig', name='Rainbow Wacky Wig'),
    HatItemType.Altis_hwt1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_weight', name='Weight Hat'),
    HatItemType.Altis_hwt2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_winter', name='Winter Hat'),
    HatItemType.Altis_hwz1: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_witch', name='Witch Hat'),
    HatItemType.Altis_hwz2: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/cc_m_acc_hat_wizard_enchanted', name='Wizard Hat'),
    HatItemType.Altis_jester_b_hat: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/apriltoons/jester_hat', texturePath='phase_13/maps/events/apriltoons/accessories/jesterblack_hat.png', name='Hat Style jester_b_hat'),
    HatItemType.Altis_jester_hat: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/apriltoons/jester_hat', texturePath='phase_13/maps/events/apriltoons/accessories/jester_hat.png', name='Hat Style jester_hat'),
    HatItemType.Altis_leaf_hat: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/thanksgiving/leaf_hat', name='Hat Style leaf_hat'),
    HatItemType.Altis_newstoon_gray_bow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', name='Hat Style newstoon_gray_bow'),
    HatItemType.Altis_nurse_hat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_sailorHat', texturePath='phase_13/maps/events/btl/accessories/tt_t_chr_avt_acc_hat_NurseHat.png', name='Hat Style nurse_hat'),
    HatItemType.Altis_outback_corkhat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/outback/corkhat', name='Hat Style outback_corkhat'),
    HatItemType.Altis_outback_geckohat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/outback/geckohat', name='Hat Style outback_geckohat'),
    HatItemType.Altis_outback_hat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/outback/slouchhat', name='Hat Style outback_hat'),
    HatItemType.Altis_painter_beret: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_painter_beret', name='Hat Style painter_beret'),
    HatItemType.Altis_plant_hat: AltisLegacyHatItemDefinition(modelPath='phase_11/models/lawbotHQ/da_plant', name='Hat Style plant_hat'),
    HatItemType.Altis_present_band: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/present_holly', name='Hat Style present_band'),
    HatItemType.Altis_pride_hairbow_ace: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/pride/cc_t_acc_bowtie_pride_ace.png', name='Hat Style pride_hairbow_ace'),
    HatItemType.Altis_pride_hairbow_aro: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/pride/cc_t_acc_bowtie_pride_aro.png', name='Hat Style pride_hairbow_aro'),
    HatItemType.Altis_pride_hairbow_bi: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/pride/cc_t_acc_bowtie_pride_bi.png', name='Hat Style pride_hairbow_bi'),
    HatItemType.Altis_pride_hairbow_gay: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/pride/cc_t_acc_bowtie_pride_gay.png', name='Hat Style pride_hairbow_gay'),
    HatItemType.Altis_pride_hairbow_genderfluid: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/pride/cc_t_acc_bowtie_pride_genderfluid.png', name='Hat Style pride_hairbow_genderfluid'),
    HatItemType.Altis_pride_hairbow_lesbian: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/pride/cc_t_acc_bowtie_pride_lesbian.png', name='Hat Style pride_hairbow_lesbian'),
    HatItemType.Altis_pride_hairbow_lgbt: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/pride/cc_t_acc_bowtie_pride_lgbt.png', name='Hat Style pride_hairbow_lgbt'),
    HatItemType.Altis_pride_hairbow_nb: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/pride/cc_t_acc_bowtie_pride_nb.png', name='Hat Style pride_hairbow_nb'),
    HatItemType.Altis_pride_hairbow_pan: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/pride/cc_t_acc_bowtie_pride_pan.png', name='Hat Style pride_hairbow_pan'),
    HatItemType.Altis_pride_hairbow_trans: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/newstoon-gray_bow', texturePath='phase_4/maps/pride/cc_t_acc_bowtie_pride_trans.png', name='Hat Style pride_hairbow_trans'),
    HatItemType.Altis_pumpkin_bucket: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_hat_pumpkinbucket', name='Hat Style pumpkin_bucket'),
    HatItemType.Altis_ragdoll_hat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/ragdoll_homemade_hat', name='Hat Style ragdoll_hat'),
    HatItemType.Altis_ragdoll_humble: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_ragdoll_humble', name='Hat Style ragdoll_humble'),
    HatItemType.Altis_ragdoll_regal: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_ragdoll_regal', name='Hat Style ragdoll_regal'),
    HatItemType.Altis_ragdoll_tradi: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_ragdoll_tradi', name='Hat Style ragdoll_tradi'),
    HatItemType.Altis_rainbow_phones: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/apriltoons/rainbowphones', name='Hat Style rainbow_phones'),
    HatItemType.Altis_ribbon_blue: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', texturePath='phase_4/maps/tt_t_chr_avt_acc_hat_ribbonBlue.png', name='Hat Style ribbon_blue'),
    HatItemType.Altis_ridinghood_hood: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/ridinghood_hood', name='Hat Style ridinghood_hood'),
    HatItemType.Altis_robophones: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/robophones', name='Hat Style robophones'),
    HatItemType.Altis_rosecrown_blue: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_rosecrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_rosecrown_blue.png', name='Hat Style rosecrown_blue'),
    HatItemType.Altis_rosecrown_cyan: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_rosecrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_rosecrown_cyan.png', name='Hat Style rosecrown_cyan'),
    HatItemType.Altis_rosecrown_green: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_rosecrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_rosecrown_green.png', name='Hat Style rosecrown_green'),
    HatItemType.Altis_rosecrown_orange: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_rosecrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_rosecrown_orange.png', name='Hat Style rosecrown_orange'),
    HatItemType.Altis_rosecrown_pink: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_rosecrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_rosecrown_pink.png', name='Hat Style rosecrown_pink'),
    HatItemType.Altis_rosecrown_purple: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_rosecrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_rosecrown_purple.png', name='Hat Style rosecrown_purple'),
    HatItemType.Altis_rosecrown_red: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_rosecrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_rosecrown_red.png', name='Hat Style rosecrown_red'),
    HatItemType.Altis_rosecrown_white: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_rosecrown', name='Hat Style rosecrown_white'),
    HatItemType.Altis_rosecrown_yellow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/ttcc_acc_rosecrown', texturePath='phase_4/maps/social/gumball/ttcc_acc_rosecrown_yellow.png', name='Hat Style rosecrown_yellow'),
    HatItemType.Altis_santa_rainbow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_santa_rainbow', name='Hat Style santa_rainbow'),
    HatItemType.Altis_santa_red: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_santa_red', name='Hat Style santa_red'),
    HatItemType.Altis_scarecrow_hat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_m_chr_avt_acc_hat_scarecrow', name='Hat Style scarecrow_hat'),
    HatItemType.Altis_seven_fedora: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_fedora', texturePath='phase_13/maps/events/btl/accessories/seven_fedora.png', name='Hat Style seven_fedora'),
    HatItemType.Altis_ski_helmet: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/ski_helmet', name='Hat Style ski_helmet'),
    HatItemType.Altis_ski_helmet_blue: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/ski_helmet', texturePath='phase_4/maps/winter/ski_helmet/ski_helmet_blue.png', name='Hat Style ski_helmet_blue'),
    HatItemType.Altis_ski_helmet_gray: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/ski_helmet', texturePath='phase_4/maps/winter/ski_helmet/ski_helmet_grey.png', name='Hat Style ski_helmet_gray'),
    HatItemType.Altis_ski_helmet_green: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/ski_helmet', texturePath='phase_4/maps/winter/ski_helmet/ski_helmet_green.png', name='Hat Style ski_helmet_green'),
    HatItemType.Altis_ski_helmet_pink: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/ski_helmet', texturePath='phase_4/maps/winter/ski_helmet/ski_helmet_pink.png', name='Hat Style ski_helmet_pink'),
    HatItemType.Altis_ski_helmet_rainbow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/ski_helmet', texturePath='phase_4/maps/winter/ski_helmet/ski_helmet_rainbow.png', name='Hat Style ski_helmet_rainbow'),
    HatItemType.Altis_ski_helmet_red: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/ski_helmet', texturePath='phase_4/maps/winter/ski_helmet/ski_helmet_red.png', name='Hat Style ski_helmet_red'),
    HatItemType.Altis_snowman_hat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/snowman_hat', name='Hat Style snowman_hat'),
    HatItemType.Altis_soldier_hat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/soldier_homemade_hat', name='Hat Style soldier_hat'),
    HatItemType.Altis_space_helm: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/tt_t_chr_avt_acc_hat_space_helm', name='Hat Style space_helm'),
    HatItemType.Altis_spin_doctor_band: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/btl/accessories/btl_spin_band', texturePath='phase_13/maps/events/btl/accessories/btl_spincjtie.png', name='Hat Style spin_doctor_band'),
    HatItemType.Altis_star_hat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_star', name='Hat Style star_hat'),
    HatItemType.Altis_stpats_band: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/stpats/cloverband', name='Hat Style stpats_band'),
    HatItemType.Altis_stpats_clip: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/stpats/cloverclip', name='Hat Style stpats_clip'),
    HatItemType.Altis_stpats_top_lucky: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/stpats/luckyhat', name='Hat Style stpats_top_lucky'),
    HatItemType.Altis_stpats_top_tart: AltisLegacyHatItemDefinition(modelPath='phase_13/models/events/stpats/tartanhat', name='Hat Style stpats_top_tart'),
    HatItemType.Altis_tin_humble: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_tin_humble', name='Hat Style tin_humble'),
    HatItemType.Altis_tin_regal: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_tin_regal', name='Hat Style tin_regal'),
    HatItemType.Altis_tin_tradi: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/winter/tt_m_chr_avt_acc_hat_tin_tradi', name='Hat Style tin_tradi'),
    HatItemType.Altis_tiw_bow: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/tt_m_chr_avt_acc_hat_ribbon', texturePath='phase_4/maps/halloween/accessories_textures/tt_t_chr_avt_acc_hat_ribbonBLACK.png', name='Hat Style tiw_bow'),
    HatItemType.Altis_tv_hat: AltisLegacyHatItemDefinition(modelPath='phase_3.5/models/props/tv', name='Hat Style tv_hat'),
    HatItemType.Altis_umbrella: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/apriltoons/tt_m_chr_avt_acc_hat_umbrella', name='Hat Style umbrella'),
    HatItemType.Altis_webster_bookhat: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/social/webster/tt_m_chr_avt_acc_hat_webster_bookhat', name='Hat Style webster_bookhat'),
    HatItemType.Altis_wizard_black: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/cc_m_acc_hat_wizard_enchanted', texturePath='phase_4/maps/halloween/accessories_textures/cc_t_acc_hat_wizard_enchanted_stars_black.png', name='Hat Style wizard_black'),
    HatItemType.Altis_wizard_blue: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/cc_m_acc_hat_wizard_enchanted', texturePath='phase_4/maps/halloween/accessories_textures/cc_t_acc_hat_wizard_enchanted_stars_blue.png', name='Hat Style wizard_blue'),
    HatItemType.Altis_wizard_green: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/cc_m_acc_hat_wizard_enchanted', texturePath='phase_4/maps/halloween/accessories_textures/cc_t_acc_hat_wizard_enchanted_stars_green.png', name='Hat Style wizard_green'),
    HatItemType.Altis_wizard_pink: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/cc_m_acc_hat_wizard_enchanted', texturePath='phase_4/maps/halloween/accessories_textures/cc_t_acc_hat_wizard_enchanted_stars_pink.png', name='Hat Style wizard_pink'),
    HatItemType.Altis_wizard_red: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/cc_m_acc_hat_wizard_enchanted', texturePath='phase_4/maps/halloween/accessories_textures/cc_t_acc_hat_wizard_enchanted_stars_red.png', name='Hat Style wizard_red'),
    HatItemType.Altis_wizard_traffic_orange: AltisLegacyHatItemDefinition(modelPath='phase_4/models/accessories/halloween/cc_m_acc_hat_wizard_enchanted', texturePath='phase_4/maps/halloween/accessories_textures/cc_t_acc_hat_wizard_enchanted_traffic_orange.png', name='Hat Style wizard_traffic_orange'),
}
