"""
Auto-ported shoe catalog from Altis's original ToonDNA.ShoesStyles.
This file is generated -- see the porting session notes for how it was produced.
"""
from __future__ import annotations
from toontown.toon.accessories.AltisLegacyAccessories import AltisLegacyShoeItemDefinition
from toontown.inventory.enums.ItemEnums import ShoeItemType

AltisLegacyShoeRegistry = {
    ShoeItemType.Altis_alchemist_shoes: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/halloween/accessories_textures/tt_t_chr_avt_acc_sho_alchemist.png', name='Shoe Style alchemist_shoes'),
    ShoeItemType.Altis_aviator_boots: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/apriltoons/aviator_outfit/aviator_boots.png', name='Shoe Style aviator_boots'),
    ShoeItemType.Altis_chair_shoes: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/social/discord/cc_t_acc_sho_promo_chairman.png', name='Shoe Style chair_shoes'),
    ShoeItemType.Altis_homemade_ragdoll_boots: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/winter/homemade_ragdoll/ragdoll_homemade_boots.png', name='Shoe Style homemade_ragdoll_boots'),
    ShoeItemType.Altis_homemade_soldier_boots: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/winter/homemade_tin_soldier/soldier_homemade_boots.png', name='Shoe Style homemade_soldier_boots'),
    ShoeItemType.Altis_hwtown_boots: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/halloween/halloweentown_outfit/hwtown_boots.png', name='Shoe Style hwtown_boots'),
    ShoeItemType.Altis_law_shoes: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_13/maps/events/apriltoons/accessories/btl_lbhq_shoes.png', name='Shoe Style law_shoes'),
    ShoeItemType.Altis_lazy_bones_shoes: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/halloween/lazy_bones_outfit/lazy_bones_shoes.png', name='Shoe Style lazy_bones_shoes'),
    ShoeItemType.Altis_outback_shoes: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/outback/outback_shoes.png', name='Shoe Style outback_shoes'),
    ShoeItemType.Altis_phantom_shoes: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_13/maps/events/halloween/phantoon_boots.png', name='Shoe Style phantom_shoes'),
    ShoeItemType.Altis_pumpkin_shoes: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_13/maps/events/btl/accessories/pumpkin_shoes.png', name='Shoe Style pumpkin_shoes'),
    ShoeItemType.Altis_ragdoll_humble: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/winter/accessories_textures/humble-ragdoll-shoes.png', name='Shoe Style ragdoll_humble'),
    ShoeItemType.Altis_ragdoll_regal: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/winter/accessories_textures/regal-ragdoll-shoes.png', name='Shoe Style ragdoll_regal'),
    ShoeItemType.Altis_ragdoll_traditional: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/winter/accessories_textures/tradi-ragdoll-shoes.png', name='Shoe Style ragdoll_traditional'),
    ShoeItemType.Altis_rainbow_shoes: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_13/maps/events/apriltoons/accessories/triplerainbow_shoes.png', name='Shoe Style rainbow_shoes'),
    ShoeItemType.Altis_retro_winterdress_shoes: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/winter/retro_winterwear/winterdress_shoes.png', name='Shoe Style retro_winterdress_shoes'),
    ShoeItemType.Altis_retro_wintersuit_shoes: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/winter/retro_winterwear/wintersuit_shoes.png', name='Shoe Style retro_wintersuit_shoes'),
    ShoeItemType.Altis_sat1: AltisLegacyShoeItemDefinition(nodeName='shoes', name='Green Athletic Shoes'),
    ShoeItemType.Altis_sat2: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_athleticRed.png', name='Red Athletic Shoes'),
    ShoeItemType.Altis_sat3: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_athleticYellow.png', name='Yellow Athletic Shoes'),
    ShoeItemType.Altis_sat4: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_athleticBlack.png', name='Black Athletic Shoes'),
    ShoeItemType.Altis_scb1: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_cowboyBoots.png', name='Cowboy Boots'),
    ShoeItemType.Altis_scs1: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_converseStyleGreen.png', name='Green Sneakers'),
    ShoeItemType.Altis_scs2: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_converseStyleBlack.png', name='Black Sneakers'),
    ShoeItemType.Altis_scs3: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_converseStyleWhite.png', name='White Sneakers'),
    ShoeItemType.Altis_scs4: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_converseStylePink.png', name='Pink Sneakers'),
    ShoeItemType.Altis_scs5: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_converseStyleRed.png', name='Red Sneakers'),
    ShoeItemType.Altis_scs6: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_converseStyleYellow.png', name='Yellow Sneakers'),
    ShoeItemType.Altis_sdk1: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_deckShoes.png', name='Boat Shoes'),
    ShoeItemType.Altis_sfb1: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_fashionBootsPurple.png', name='Purple Boots'),
    ShoeItemType.Altis_sfb2: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_fashionBootsBlueSquares.png', name='Blue Square Boots'),
    ShoeItemType.Altis_sfb3: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_fashionBootsGreenHearts.png', name='Green Hearts Boots'),
    ShoeItemType.Altis_sfb4: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_fashionBootsGreyDots.png', name='Grey Dots Boots'),
    ShoeItemType.Altis_sfb5: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_fashionBootsOrangeStars.png', name='Orange Stars Boots'),
    ShoeItemType.Altis_sfb6: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_fashionBootsPinkStars.png', name='Pink Stars Boots'),
    ShoeItemType.Altis_shoes_cardBlack: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/social/gumball/ttcc_acc_cardBoots_black.png', name='Shoe Style shoes_cardBlack'),
    ShoeItemType.Altis_shoes_cardRed: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/social/gumball/ttcc_acc_cardBoots_red.png', name='Shoe Style shoes_cardRed'),
    ShoeItemType.Altis_shoes_cyberpunk: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/social/cyberpunk/cc_t_acc_shoes_cyberpunk.png', name='Shoe Style shoes_cyberpunk'),
    ShoeItemType.Altis_shoes_diver: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/bosses/shoes_diver.png', name='Shoe Style shoes_diver'),
    ShoeItemType.Altis_shoes_engineer: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/social/gumball/ttcc_acc_engineer_shoes.png', name='Shoe Style shoes_engineer'),
    ShoeItemType.Altis_shoes_fruitpie: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/social/gumball/ttcc_acc_fruitpieshoes.png', name='Shoe Style shoes_fruitpie'),
    ShoeItemType.Altis_shoes_gatekeeper: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/bosses/ttcc_acc_armored_boots.png', name='Shoe Style shoes_gatekeeper'),
    ShoeItemType.Altis_shoes_gator: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/social/gumball/ttcc_acc_gator_shoes.png', name='Shoe Style shoes_gator'),
    ShoeItemType.Altis_shoes_painter: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/social/gumball/ttcc_acc_painter_shoes.png', name='Shoe Style shoes_painter'),
    ShoeItemType.Altis_shoes_pirate_ghost: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/halloween/accessories_textures/cc_t_acc_sho_md_pirate_ghost_green.png', name='Shoe Style shoes_pirate_ghost'),
    ShoeItemType.Altis_shoes_spy: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/halloween/accessories_textures/cc_t_acc_sho_md_spy_purple.png', name='Shoe Style shoes_spy'),
    ShoeItemType.Altis_sht1: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_hiTopSneakers.png', name='Green Hi Top Sneakers'),
    ShoeItemType.Altis_sht2: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_hiTopSneakersPink.png', name='Pink Hi Top Sneakers'),
    ShoeItemType.Altis_shw1: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_pirate.png', name='Pirate Shoes'),
    ShoeItemType.Altis_shw2: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_dinosaur.png', name='Toonosaur Feet'),
    ShoeItemType.Altis_skeleton_shoes: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/halloween/accessories_textures/tt_t_chr_avt_acc_sho_skeleton.png', name='Shoe Style skeleton_shoes'),
    ShoeItemType.Altis_slf1: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_loafers.png', name='Loafers'),
    ShoeItemType.Altis_smb1: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_3/maps/tt_t_chr_avt_acc_sho_docMartinBootsGreen.png', name='Green Toon Boots'),
    ShoeItemType.Altis_smb2: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_docMartinBootsAqua.png', name='Aqua Toon Boots'),
    ShoeItemType.Altis_smb3: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_docMartinBootsBrown.png', name='Brown Toon Boots'),
    ShoeItemType.Altis_smb4: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_docMartinBootsYellow.png', name='Yellow Toon Boots'),
    ShoeItemType.Altis_smb5: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_docMartinBootsPink.png', name='Pink Toon Boots'),
    ShoeItemType.Altis_smj1: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_maryJaneShoes.png', name='Black Fancy Shoes'),
    ShoeItemType.Altis_smj2: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_maryJaneShoesBrown.png', name='Brown Fancy Shoes'),
    ShoeItemType.Altis_smj3: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_maryJaneShoesRed.png', name='Red Fancy Shoes'),
    ShoeItemType.Altis_smj4: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_maryJaneShoesPurple.png', name='Purple Fancy Shoes'),
    ShoeItemType.Altis_smt1: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_motorcycleBoots.png', name='Motorcycle Boots'),
    ShoeItemType.Altis_sox1: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_oxfords.png', name='Oxfords'),
    ShoeItemType.Altis_space_boots: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/halloween/accessories_textures/tt_t_chr_avt_acc_sho_space_boots.png', name='Shoe Style space_boots'),
    ShoeItemType.Altis_srb1: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_rainBootsPink.png', name='Pink Rain Boots'),
    ShoeItemType.Altis_srb2: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_rainBootsRedDots.png', name='Red Dots Rain Boots'),
    ShoeItemType.Altis_srb3: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_rainBootsBlue.png', name='Blue Rain Boots'),
    ShoeItemType.Altis_srb4: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_rainBootsYellow.png', name='Yellow Rain Boots'),
    ShoeItemType.Altis_ssb1: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_superToonRedBoots.png', name='Red Super Toon Boots'),
    ShoeItemType.Altis_sst1: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_santaBoots.png', name='Jolly Boots'),
    ShoeItemType.Altis_sts1: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_tennisShoesGreen.png', name='Green Tennis Shoes'),
    ShoeItemType.Altis_sts2: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_tennisShoesPink.png', name='Pink Tennis Shoes'),
    ShoeItemType.Altis_sts3: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_tennisShoesPurple.png', name='Purple Tennis Shoes'),
    ShoeItemType.Altis_sts4: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_tennisShoesViolet.png', name='Violet Tennis Shoes'),
    ShoeItemType.Altis_sts5: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_tennisShoesYellow.png', name='Yellow Tennis Shoes'),
    ShoeItemType.Altis_swb1: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_winterBootsBeige.png', name='Beige Winter Boots'),
    ShoeItemType.Altis_swb2: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_winterBootsPink.png', name='Pink Winter Boots'),
    ShoeItemType.Altis_swk1: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_workBoots.png', name='Work Boots'),
    ShoeItemType.Altis_swt1: AltisLegacyShoeItemDefinition(nodeName='shoes', texturePath='phase_4/maps/tt_t_chr_avt_acc_sho_wingtips.png', name='Wingtips'),
    ShoeItemType.Altis_tin_humble: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/winter/accessories_textures/humble-tinsoldier-shoes.png', name='Shoe Style tin_humble'),
    ShoeItemType.Altis_tin_regal: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/winter/accessories_textures/regal-tinsoldier-shoes.png', name='Shoe Style tin_regal'),
    ShoeItemType.Altis_tin_traditional: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/winter/accessories_textures/tradi-tinsoldier-shoes.png', name='Shoe Style tin_traditional'),
    ShoeItemType.Altis_tumbles_shoes: AltisLegacyShoeItemDefinition(nodeName='boots_short', texturePath='phase_4/maps/tumbles/tumbles_shoes.png', name='Shoe Style tumbles_shoes'),
    ShoeItemType.Altis_vintage_snow_outfit: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/winter/vintage_snow_outfit/tt_t_chr_avt_acc_sho_vintage_snow.png', name='Shoe Style vintage_snow_outfit'),
    ShoeItemType.Altis_wingsuit_boots: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/apriltoons/wingsuit_outfit/wingsuit_boots.png', name='Shoe Style wingsuit_boots'),
    ShoeItemType.Altis_witch_shoes: AltisLegacyShoeItemDefinition(nodeName='boots_long', texturePath='phase_4/maps/halloween/accessories_textures/tt_t_chr_avt_acc_sho_witch.png', name='Shoe Style witch_shoes'),
}
