"""
This file contains all defined information regarding suit animations.
Additionally, simple Cog attack animations are defined below,
defined inside of their appropriate phase file.
"""

# list of anims for all suit parts
AllSuits = (
    ('walk', 'walk'), ('run', 'walk'), ('neutral', 'neutral'), ('shuffle-left', 'shuffle-left'),
    ('shuffle-right', 'shuffle-right'),
)
AllSuitsMinigame = (('victory', 'victory'),
 ('flail', 'flailing'),
 ('tug-o-war', 'tug-o-war'),
 ('slip-backward', 'slip-backward'),
 ('slip-forward', 'slip-forward'))
AllSuitsTutorialBattle = (('lose', 'lose'), ('skeleton-lose', 'skeleton-lose'), ('pie-small-react', 'pie-small'), ('squirt-small-react', 'squirt-small'))
AllSuitsBattle = (('drop-react', 'anvil-drop'),
 ('flatten', 'drop'),
 ('flail-qs', 'flailing-qs'),
 ('flail-wb', 'flailing-wb'),
 ('sidestep-left', 'sidestep-left'),
 ('sidestep-right', 'sidestep-right'),
 ('gag-miss', 'gag-miss'),
 ('squirt-large-react', 'squirt-large'),
 ('landing', 'landing'),
 ('reach', 'walknreach'),
 ('reach-bill', 'walknreach-bill'),
 ('rake-react', 'rake'),
 ('hypnotized', 'hypnotize'),
 ('pie-large-react', 'pie-large'),
 ('pie-large-react-lured', 'pie-large-lured'),
 ('small-zap', 'small-zap'),
 ('large-zap', 'large-zap'),
 ('soak', 'soak'),
 ('headless-death', 'headless-death'),
 ('wrecked', 'wrecked'),
 ('lured', 'lured'),
 ('magnet', 'magnet'),
 ('pie-large-react', 'pie-large'),
 ('pie-large-react-lured', 'pie-large-lured'),
 ('sound-react', 'sound-react'),
 ('sound-react-nt', 'sound-react-nt'),
 ('sound-react-bow', 'sound-react-bow'))
# Extra Suit anims is exclusively for the cutscene editor at this time.
ExtraSuitAnims = (
    ('count-neutral', 'count-neutral'),
    ('true-neutral', 'neutral'),
    ('mob-mentality', 'mob-mentality'),
    ('magic3', 'magic3'),
    ('magic3-alt', 'magic3-alt'),
    ('taunt', 'taunt'),
    ('quick-jump', 'quick-jump',),
    ('song-and-dance', 'song-and-dance'),
    ('stomp', 'stomp'),
    ('effort', 'effort'),
    ('finger-wag', 'finger-wag'),
    ('come-on', 'come-on'),
    ('death-pose', 'death-pose'),
    ('overclocked', 'overclocked'),
    ('lunch-start', 'lunch-start'),
    ('lunch-loop', 'lunch-loop'),
    ('lunch-end', 'lunch-end'),
    ('sit-lose', 'sit-lose'),
    ('sit', 'sit'),
    ('sit-angry', 'sit-angry'),
    ('rage', 'rage'),
    ('transformation', 'transformation'),
    ('objection-in', 'objection-in'),
    ('objection-loop', 'objection-loop'),
    ('objection-out', 'objection-out'),
    ('rushjob', 'rushjob'),
    ('rolled', 'rolled'),
    ('sit-hungry-left', 'sit-hungry-left'),
    ('leap', 'chainsaw-cutscene-leap'),
    ('getup', 'chainsaw-cutscene-getup'),
    ('hurt-neutral', 'chainsaw-cutscene-hurt-neutral'),
    ('hurt-walk', 'chainsaw-cutscene-hurt-walk'),
    ('laying', 'chainsaw-cutscene-laying'),
    ('todesk', 'chainsaw-cutscene-todesk'),
    ('desk-neutral', 'chainsaw-cutscene-desk-neutral'),
    ('pull-slots', 'pull-slots'),
    ('sit-dock', 'sit-dock'),
    ('sparkplug', 'sparkplug'),
    ('revvedup', 'revvedup'),
    ('throttle', 'throttle'),
    ('throttletwo', 'throttletwo'),
    ('emergeHead', 'emergeHead'),
    ('scabbard', 'scabbard'),
    ('sit-dock', 'sit-dock'),
    ('sit-dock-turn-neutral', 'sit-dock-turn-neutral'),
    ('sit-dock-turn', 'sit-dock-turn'),
    ('sit-dock-stand', 'sit-dock-stand'),
    ('mplayer-caress', 'mplayer-caress'),
    ('mplayer-kneel-caress-into', 'mplayer-kneel-caress-into'),
    ('mplayer-kneel-caress-out', 'mplayer-kneel-caress-out'),
    ('mplayer-kneel-into', 'mplayer-kneel-into'),
    ('mplayer-kneel-neutral', 'mplayer-kneel-neutral'),
    ('mplayer-kneel-out', 'mplayer-kneel-out'),
    ('wheelspin', 'wheelspin'),
    ('awalk', 'awalk'),
    ('snap', 'snap'),
    ('bellow', 'bellow'),
    ('rage-sgoat', 'rage-sgoat'),
    ('neutral-enraged', 'neutral-enraged'),
    ('sticker', 'sticker'),
    ('throw-insurance', 'throw-insurance', 11),
    ('ds-fusion-shot1', 'fusiondance-shot1', 10),
    ('ds-fusion-shot2', 'fusiondance-shot2', 10),
    ('ds-fusion-shot3', 'fusiondance-shot3', 10),
    ('ds-fusion-shot4', 'fusiondance-shot4', 10),
    ('ds-fusion-shot5', 'fusiondance-shot5', 10),
    ('hr-fusion-shot1', 'highroller-fusiondance-shot1', 12),
    ('hr-fusion-shot2', 'highroller-fusiondance-shot2', 12),
    ('hr-fusion-shot3', 'highroller-fusiondance-shot3', 12),
    ('hr-fusion-shot4', 'highroller-fusiondance-shot4', 12),
    ('hr-fusion-shot5', 'highroller-fusiondance-shot5', 12),
    ('mp-fusion-shot1', 'majorplayer-fusiondance-shot1', 12),
    ('mp-fusion-shot2', 'majorplayer-fusiondance-shot2', 12),
    ('mp-fusion-shot3', 'majorplayer-fusiondance-shot3', 12),
    ('mp-fusion-shot4', 'majorplayer-fusiondance-shot4', 12),
    ('mp-fusion-shot5', 'majorplayer-fusiondance-shot5', 12),
)
# Extra Suit head anims is exclusively for the cutscene editor at this time.
ExtraSuitHeadAnims = (
    ('come-on', 'come-on'),
    ('overclocked', 'overclocked'),
    ('lunch-start', 'lunch-start'),
    ('lunch-loop', 'lunch-loop'),
    ('lunch-end', 'lunch-end'),
    ('leap', 'chainsaw-cutscene-leap'),
    ('getup', 'chainsaw-cutscene-getup'),
    ('hurt-neutral', 'chainsaw-cutscene-hurt-neutral'),
    ('hurt-walk', 'chainsaw-cutscene-hurt-walk'),
    ('laying', 'chainsaw-cutscene-laying'),
    ('todesk', 'chainsaw-cutscene-todesk'),
    ('desk-neutral', 'chainsaw-cutscene-desk-neutral'),
    ('revvedup', 'revvedup'),
    ('sparkplug', 'sparkplug'),
    ('scabbard', 'scabbard'),
    ('throttle', 'throttle'),
    ('throttle2', 'throttle2'),
    ('wheelspin', 'wheelspin'),
    ('fusiondance-shot1', 'fusiondance-shot1'),
    ('fusiondance-shot2', 'fusiondance-shot2'),
    ('fusiondance-shot3', 'fusiondance-shot3'),
    ('fusiondance-shot4', 'fusiondance-shot4'),
    ('fusiondance-shot5', 'fusiondance-shot5'),
    ('ace-in-the-hole', 'ace-in-the-hole'),
    ('bellow', 'bellow'),
    ('gator-snap', 'gator-snap'),
    ('enraged', 'enraged'),
    ('insurance', 'insurance')
)
SuitsCEOBattle = (('sit', 'sit'),
 ('sit-eat-in', 'sit-eat-in'),
 ('sit-eat-loop', 'sit-eat-loop'),
 ('sit-eat-out', 'sit-eat-out'),
 ('sit-angry', 'sit-angry'),
 ('sit-hungry-left', 'leftsit-hungry'),
 ('sit-hungry-right', 'rightsit-hungry'),
 ('sit-lose', 'sit-lose'),
 ('tray-walk', 'tray-walk'),
 ('tray-neutral', 'tray-neutral'),
 ('sit-lose', 'sit-lose'))

SuitAAnims = [
    ('defense', 'defense', 11),
    ('bellow', 'bellow', 11),
    ('gavel', 'gavel', 8),
    ('cease', 'cease', 5),
    ('frustrated', 'frustrated', 5),
    ('frustrated-f', 'frustrated-f', 5),
    ('effort', 'effort', 5),
    ('smile', 'smile', 5),
    ('glower', 'glower', 5),
    ('quick-jump', 'jump', 6),
    ('sanction', 'sanction', 11),
    ('pen-squirt', 'fountain-pen', 7),
    ('magic1', 'magic1', 5),
    ('finger-wag', 'fingerwag', 5),
    ('throw-paper', 'throw-paper', 5),
    ('pickpocket', 'pickpocket', 5),
    ('song-and-dance', 'song-and-dance', 8),
    ('cigar-smoke', 'cigar-smoke', 8),
    ('magic3', 'magic3', 5),
    ('magic3-alt', 'magic3-alt', 5),
    ('phone', 'phone', 5),
    ('calculator', 'calculator', 5),
    ('speak', 'speak', 5),
    ('rubber-stamp', 'rubber-stamp', 5),
    ('snap', 'snap', 11),
    ('snap-override', 'snap-override', 12),
    ('throw-object', 'throw-object', 5),
    ('magic2', 'magic2', 5),
    ('roll-o-dex', 'roll-o-dex', 5),
    ('golf-club-swing', 'golf-club-swing', 5),
    ('mob-mentality', 'mob-mentality', 5),
    ('taunt', 'taunt', 5),
    ('defeated-into', 'defeated-into', 5),
    ('defeated-loop', 'defeated-loop', 5),
    ('defeated-out', 'defeated-out', 5),
    ('rolled', 'rolled', 12),
    ('turn-into', 'turn-into', 5),
    ('turn-loop', 'turn-loop', 5),
    ('turn-out', 'turn-out', 5),
    ('awalk', 'awalk', 5),
    ('gag-miss', 'gag-miss', 5),
    ('pie-large-react', 'pie-large', 5),
    ('pie-large-react-lured', 'pie-large-lured', 5),
    ('sound-react', 'sound-react', 5),
    ('sound-react-bow', 'sound-react-bow', 5),
    ('sound-react-nt', 'sound-react-nt', 5),
    ('falling-knife', 'falling-knife', 5),
    ('blue-chip', 'blue-chip', 5),
    ('sticker', 'sticker', 5),
]
SuitBAnims = [
    ('defense', 'defense', 11),
    ('stomp', 'stomp', 5),
    ('pencil-sharpener', 'pencil-sharpener', 5),
    ('effort', 'effort', 5),
    ('quick-jump', 'jump', 6),
    ('magic1', 'magic1', 5),
    ('throw-paper', 'throw-paper', 5),
    ('pickpocket', 'pickpocket', 5),
    ('finger-wag', 'finger-wag', 5),
    ('objection-out', 'objection-out', 5),
    ('magic3', 'magic3', 5),
    ('phone', 'phone', 5),
    ('calculator', 'calculator', 5),
    ('objection-loop', 'objection-loop', 5),
    ('speak', 'speak', 5),
    ('pen-squirt', 'pen-squirt', 5),
    ('rage', 'rage', 11),
    ('objection-in', 'objection-in', 5),
    ('frustrated', 'frustrated', 5),
    ('throw-object', 'throw-object', 5),
    ('hold-pencil', 'hold-pencil', 5),
    ('magic2', 'magic2', 5),
    ('hold-eraser', 'hold-eraser', 5),
    ('slap', 'slap', 5),
    ('roll-o-dex', 'roll-o-dex', 5),
    ('mob-mentality', 'mob-mentality', 5),
    ('sit-dock', 'sit-dock', 5),
    ('sit-dock-turn-neutral', 'sit-dock-turn-neutral', 5),
    ('sit-dock-turn', 'sit-dock-turn', 5),
    ('sit-dock-stand', 'sit-dock-stand', 5),
    ('transformation', 'transformation', 5),
    ('glower', 'glower', 5),
    ('smile',  'smile', 5),
    ('rushjob',  'rushjob', 9),
    ('gag-miss', 'gag-miss', 5),
    ('pie-large-react', 'pie-large', 5),
    ('pie-large-react-lured', 'pie-large-lured', 5),
    ('sound-react', 'sound-react', 5),
    ('sound-react-bow', 'sound-react-bow', 5),
    ('sound-react-nt', 'sound-react-nt', 5),
    ('blue-chip', 'blue-chip', 5),
    ('short-squeeze', 'short-squeeze', 5),
    ('sticker', 'sticker', 5),
]
SuitCAnims = [
    ('throw-paper', 'throw-paper', 3.5),
    ('throw-object', 'throw-object', 5),
    ('effort', 'effort', 5),
    ('glower', 'glower', 5),
    ('phone', 'phone', 3.5),
    ('calculator', 'calculator', 5),
    ('magic1', 'magic1', 5),
    ('shredder', 'shredder', 3.5),
    ('watercooler', 'watercooler', 5),
    ('pickpocket', 'pickpocket', 5),
    ('finger-wag', 'finger-wag', 5),
    ('speak', 'speak', 5),
    ('rubber-stamp', 'rubber-stamp', 5),
    ('magic3', 'magic2', 5),
    ('magic2', 'magic2', 5),
    ('pen-squirt', 'fountain-pen', 5),
    ('mob-mentality', 'mob-mentality', 5),
    ('gag-miss', 'gag-miss', 5),
    ('pie-large-react', 'pie-large', 5),
    ('pie-large-react-lured', 'pie-large-lured', 5),
    ('sound-react', 'sound-react', 5),
    ('sound-react-bow', 'sound-react-bow', 5),
    ('sound-react-nt', 'sound-react-nt', 5),
    ('falling-knife', 'falling-knife', 5),
    ('short-squeeze', 'short-squeeze', 5),
    ('sticker', 'sticker', 5),
    ('pencil-sharpener', 'pencil-sharpener', 5)  # unused TTO animation
]

AdditionalSuitAnims = {
    'caseman': [
        ('throw-insurance', 'throw-insurance', 11),
    ],
    'sgoat': [
        ('neutral-enraged', 'neutral-enraged', 11),
        ('neutral-enraged-return', 'neutral-enraged-return', 11),
        ('rage-sgoat', 'rage-sgoat', 11),
    ],
    'stenog': [
        ('calculating-costs', 'calculating-costs', 11),
    ],
    'mslacker': [
        ('lunch-start', 'lunch-start', 9),
        ('lunch-loop', 'lunch-loop', 9),
        ('lunch-end', 'lunch-end', 9)
    ],
    'psetter': [
        ('neutral', 'pace', 9),
        ('true-neutral', 'neutral', 4),
        ('come-on', 'come-on', 9),
        ('death-pose', 'death-pose', 9),
        ('overclocked', 'overclocked', 9),
    ],
    'ottoman': [
        ('sit', 'ottoman-sit-loop', 5),
        ('writing-start', 'ottoman-writing-start', 5),
        ('writing', 'ottoman-writing-loop', 5),
        ('writing-stop', 'ottoman-writing-stop', 5),
        ('wallet-start', 'ottoman-wallet-start', 5),
        ('wallet', 'ottoman-wallet-loop', 5),
        ('wallet-stop', 'ottoman-wallet-stop', 5),
        ('yawn', 'ottoman-yawn', 5),
    ],
    'clerk': [
        ('objection-in', 'objection-in', 5),
        ('objection-loop', 'objection-loop', 5),
        ('objection-out', 'objection-out', 5),
    ],
    'duckshfl': [
        ('pull-slots', 'pull-slots', 10),
        ('ds-fusion-shot1', 'fusiondance-shot1', 10),
        ('ds-fusion-shot2', 'fusiondance-shot2', 10),
        ('ds-fusion-shot3', 'fusiondance-shot3', 10),
        ('ds-fusion-shot4', 'fusiondance-shot4', 10),
        ('ds-fusion-shot5', 'fusiondance-shot5', 10),
    ],
    'mplayer': [
        ('neutral', 'rolled', 12),
        ('true-neutral', 'neutral', 4),
        ('caress', 'caress', 12),
        ('kneel-caress-into', 'kneel-caress-into', 12),
        ('kneel-caress-out', 'kneel-caress-out', 12),
        ('kneel-into', 'kneel-into', 12),
        ('kneel-neutral', 'kneel-neutral', 12),
        ('kneel-out', 'kneel-out', 12),
        ('down', 'mplayer-down', 12),
        ('left', 'mplayer-left', 12),
        ('right', 'mplayer-right', 12),
        ('up', 'mplayer-up', 12),
        ('mplayer-caress', 'mplayer-caress', 12),
        ('mplayer-kneel-caress-into', 'mplayer-kneel-caress-into', 12),
        ('mplayer-kneel-caress-out', 'mplayer-kneel-caress-out', 12),
        ('mplayer-kneel-into', 'mplayer-kneel-into', 12),
        ('mplayer-kneel-neutral', 'mplayer-kneel-neutral', 12),
        ('mplayer-kneel-out', 'mplayer-kneel-out', 12),
        ('mp-fusion-shot1', 'majorplayer-fusiondance-shot1', 12),
        ('mp-fusion-shot2', 'majorplayer-fusiondance-shot2', 12),
        ('mp-fusion-shot3', 'majorplayer-fusiondance-shot3', 12),
        ('mp-fusion-shot4', 'majorplayer-fusiondance-shot4', 12),
        ('mp-fusion-shot5', 'majorplayer-fusiondance-shot5', 12),
    ],
    'ddiver': [
        ('dive', 'dive', 14),
        ('emergeHead', 'emergeHead', 14),
        ('exitWater', 'exitWater', 14),
        ('underwaterHit', 'underwaterHit', 14),
        ('underwater-sidestep', 'underwater-sidestep', 14),
    ],
    'fires': [
        ('cigar-smoke', 'firestarter-cigar-smoke', 12),
        ('summon', 'summon', 5),
    ],
    'pcrat': [
        ('cigar-smoke', 'plutocrat-cigar-smoke', 10)
    ],
    'chainsaw': [
        ('deadwood', 'deadwood', 12),
        ('layoffs', 'layoffs', 12),
        ('revvedup', 'revvedup', 12),
        ('scabbard', 'scabbard', 12),
        ('sparkplug', 'sparkplug', 12),
        ('throttle', 'throttle', 12),
        ('throttletwo', 'throttletwo', 12),
        ('leap', 'chainsaw-cutscene-leap', 12),
        ('getup', 'chainsaw-cutscene-getup', 12),
        ('hurt-neutral', 'chainsaw-cutscene-hurt-neutral', 12),
        ('hurt-walk', 'chainsaw-cutscene-hurt-walk', 12),
        ('laying', 'chainsaw-cutscene-laying', 12),
        ('todesk', 'chainsaw-cutscene-todesk', 12),
        ('desk-neutral', 'chainsaw-cutscene-desk-neutral', 12),
        ('summon', 'summon', 5),
        ('neutral-override', 'neutral-override', 12),
        ('neutral-override-glitched', 'neutral-override-glitched', 12),
    ],
    'hho': [
        ('headhoncho-cigar-smoke', 'headhoncho-cigar-smoke', 14),
    ],

    # Events
    'ftf_l': [
        ('come-on', 'come-on', 9),
        ('pace', 'pace', 9),
    ],
    'hroller': [
        ('mplayer-kneel-into', 'mplayer-kneel-into', 12),
        ('mplayer-kneel-neutral', 'mplayer-kneel-neutral', 12),
        ('mplayer-kneel-out', 'mplayer-kneel-out', 12),
        ('wheelspin', 'wheelspin', 12),
        ('hr-fusion-shot1', 'highroller-fusiondance-shot1', 12),
        ('hr-fusion-shot2', 'highroller-fusiondance-shot2', 12),
        ('hr-fusion-shot3', 'highroller-fusiondance-shot3', 12),
        ('hr-fusion-shot4', 'highroller-fusiondance-shot4', 12),
        ('hr-fusion-shot5', 'highroller-fusiondance-shot5', 12),
    ],
    'hrollerc': [
        ('neutral', 'rolled', 12),
        ('hr-fusion-shot5', 'highroller-fusiondance-shot5', 12),
        ('wheelspin', 'wheelspin', 12),
        ('mplayer-kneel-into', 'mplayer-kneel-into', 12),
    ],
}

# for debug/tool use only
AllSuitAAnims = SuitAAnims + AdditionalSuitAnims['mplayer'] + AdditionalSuitAnims['chainsaw'] + AdditionalSuitAnims['hroller']
AllSuitBAnims = SuitBAnims + AdditionalSuitAnims['psetter'] + AdditionalSuitAnims['ottoman'] + AdditionalSuitAnims['duckshfl'] + AdditionalSuitAnims['clerk']
AllSuitCAnims = SuitCAnims + AdditionalSuitAnims['ddiver'] + AdditionalSuitAnims['mslacker'] + AdditionalSuitAnims['pcrat']
