from typing import Dict, Type

from .VisualEffects import *
from .VisualEffectEnums import VisualEffectEnum

VisualEffectList: Dict[VisualEffectEnum, Type[VisualEffectBase]] = {
    VisualEffectEnum.NOTHING: BlankVisualEffect,
    VisualEffectEnum.LURED: SuitLuredVisualEffect,
    VisualEffectEnum.SOAKED: AvatarSoakedVisualEffect,
    VisualEffectEnum.DRENCHED: AvatarDrenchedVisualEffect,
    VisualEffectEnum.SPLAT: AvatarSplatVisualEffect,
    VisualEffectEnum.SUED: SuitSuedVisualEffect,
    VisualEffectEnum.SKELECOG: SkelecogVisualEffect,
    VisualEffectEnum.TOON_BOOST: ToonBoostVisualEffect,
    VisualEffectEnum.VULNERABLE: VulnerableVisualEffect,
    VisualEffectEnum.SCAPEGOAT_ENRAGED: ScapegoatEnragedVisualEffect,
    VisualEffectEnum.INSURANCE: CaseManagerHotVisualEffect,
    VisualEffectEnum.ERFIT_REVIVE: ErfitReviveVisualEffect,
    VisualEffectEnum.LEGALLY_BOUND: CaseManagerDotVisualEffect,
    VisualEffectEnum.GAG_DOWN: GagDownVisualEffect,
    VisualEffectEnum.OVERCHARGED: OverchargedVisualEffect,
    VisualEffectEnum.OC_FOREMAN: OcForemanVisualEffect,
    VisualEffectEnum.DISRUPTIVE_ADVERTISEMENT: DisruptiveAdvertisementVisualEffect,
    VisualEffectEnum.INK_DRAIN: InkDrainVisualEffect,
    VisualEffectEnum.EXTRA_GLOWER_POWERS: ExtraGlowerPowersVisualEffect,
    VisualEffectEnum.UNITE_COOLDOWN: UniteCooldownVisualEffect,
    VisualEffectEnum.COGS_DAMAGE_DOWN: CogDamageDownVisualEffect,
    VisualEffectEnum.TOONS_ACCURACY_UP: ToonsAccuracyUpVisualEffect,
    VisualEffectEnum.FROZEN: AvatarFrozenVisualEffect,
    VisualEffectEnum.TOON_BECOME_DUCK: ChangeSpeciesVisualEffect,
    VisualEffectEnum.DIVING: DivingVisualEffect,
    VisualEffectEnum.BACKBURNER: BackBurnerVisualEffect,
    VisualEffectEnum.PEELED: PeeledVisualEffect,
    VisualEffectEnum.WOODCHIPPED: WoodchippedVisualEffect,
    VisualEffectEnum.OVERHIRE: OverhireVisualEffect,
    VisualEffectEnum.TRIAL_BY_FIRE: TrialByFireVisualEffect,
    VisualEffectEnum.CORE_COMPETENCY: CoreCompetencyVisualEffect,
    VisualEffectEnum.DEEP_FREEZE: DeepFreezeVisualEffect,
    VisualEffectEnum.RUSH_JOB: RushJobVisualEffect,
    VisualEffectEnum.AFTERIMAGE: AfterimageVisualEffect,
    VisualEffectEnum.MANDATORY_LUNCH_MSLACKER: FakeMultislackerVisualEffect,
    VisualEffectEnum.ENCORE: EncoreVisualEffect,
    VisualEffectEnum.WINDED: WindedVisualEffect,
    VisualEffectEnum.CHEER: CheerVisualEffect,
    VisualEffectEnum.PRETHINKER_BRAIN_STORM: PrethinkerBrainStormVisualEffect,
    VisualEffectEnum.POWER_NAP: PowerNapVisualEffect,
    VisualEffectEnum.BEWITCHMENT: BewitchmentVisualEffect,
    VisualEffectEnum.SLUSH_FUND: SlushFundVisualEffect,
    VisualEffectEnum.MARKET_BUBBLE: MarketBubbleVisualEffect,
    VisualEffectEnum.CHAIN_LINKED: ChainLinkedVisualEffect,
    VisualEffectEnum.SPARK_PLUG_DAMAGE: SparkPlugVisualEffect,
    VisualEffectEnum.MARKED_WOOD: MarkedWoodVisualEffect,
    VisualEffectEnum.MOUTHPIECE_BONUS: MouthpieceBonusVisualEffect,
    VisualEffectEnum.BAKERY_AFICIONADO: BakeryAficionadoVisualEffect,
    VisualEffectEnum.RED_THREAD: RedThreadVisualEffect,
    VisualEffectEnum.HIGHROLLER_COMMERCIAL: HighRollerCommercialVisualEffect,
    VisualEffectEnum.HIGHROLLER_TRIVIA: HighRollerTriviaVisualEffect,
    VisualEffectEnum.HIGHROLLER_CLONE: HighRollerCloneVisualEffect,
    VisualEffectEnum.JOGGING: JoggingVisualEffect,
    VisualEffectEnum.ROLLED: RolledVisualEffect,
    VisualEffectEnum.FTF_ATTORNEY_JOGGING: FTFAttorneyJoggingEffect,
    VisualEffectEnum.HR_UNTOUCHABLE: HRUntouchableVisualEffect,
    VisualEffectEnum.CONFUSION: ConfusionVisualEffect,
    VisualEffectEnum.CHAINSAW_OVERRIDE: ChainsawOverrideVisualEffect,
    VisualEffectEnum.CHAINSAW_OVERRIDE_GLITCHED: ChainsawOverrideGlitchedVisualEffect,
}
