from toontown.nametag import NametagGlobals
from direct.interval.IntervalGlobal import *
from toontown.clashbattle.battle import MovieUtil
from toontown.clashbattle.battle.BattleBase import *
from toontown.clashbattle.battle.distributed.DistributedBattleBase import DistributedBattleBase
from otp import *
from toontown.clashsuit.suit.DistributedSuitBase import DistributedSuitBase

from toontown.toon.DistributedToonBase import DistributedToonBase


class DistributedBattleFinal(DistributedBattleBase):
    CAM_SUIT_JOINING_POS = (
        (20, -7, 7, 60, 0, 0),
        (-20, -7, 7, -60, 0, 0)
    )
    CAM_INITIAL_SUIT_JOINING_POS = (
        (25, -11, 7, 60, 0, 0),
        (-25, -11, 7, -60, 0, 0)
    )
    # Add a new ReservesJoining state to the battle FSM
    defaultTransitions = DistributedBattleBase.defaultTransitions.copy()
    defaultTransitions.update({
        "ReservesJoining": ["WaitForJoin", "WaitForInput", "Resume"],
    })
    for state in ("Off", "WaitForJoin", "PlayMovie"):
        defaultTransitions[state].append("ReservesJoining")

    def __init__(self, cr):
        townBattle = cr.playGame.hood.loader.townBattle
        DistributedBattleBase.__init__(self, cr, townBattle)

        self.setupCollisions(self.uniqueBattleName('battle-collide'))

        self.bossCog = None
        self.bossCogRequest = None
        self.streetBattle = 0
        self.initialReservesJoiningDone = False

        self.joiningSuitsName = self.uniqueBattleName('joiningSuits')

    def disable(self):
        DistributedBattleBase.disable(self)
        base.cr.relatedObjectMgr.abortRequest(self.bossCogRequest)
        self.bossCogRequest = None
        self.bossCog = None

    def delete(self):
        DistributedBattleBase.delete(self)
        self.removeCollisionData()

    ##### Messages From The Server #####

    def setBossCogId(self, bossCogId):
        self.bossCogId = bossCogId
        if bossCogId in base.cr.doId2do:
            # This would be risky if we had toons entering the zone during
            # a battle--but since all the toons are always there from the
            # beginning, we can be confident that the BossCog has already
            # been generated by the time we receive the generate for its
            # associated battles.
            # RAU slightly modified so I can spy on the lawbot boss battle
            tempBossCog = base.cr.doId2do[bossCogId]
            self.__gotBossCog([tempBossCog])
        else:
            self.notify.debug('doing relatedObjectMgr.request for bossCog')
            self.bossCogRequest = base.cr.relatedObjectMgr.requestObjects([bossCogId], allCallback=self.__gotBossCog)

    def __gotBossCog(self, bossCogList):
        self.bossCogRequest = None
        self.bossCog = bossCogList[0]

        # Now that we know the BossCog, we can check to see if we
        # should have enabled collisions when we went into the
        # NoLocalToon state.
        currStateName = self.localToonFsm.getCurrentState().getName()
        if currStateName == 'NoLocalToon' and self.bossCog.hasLocalToon():
            self.enableCollision()

    def setBattleNumber(self, battleNumber):
        self.battleNumber = battleNumber

    def setBattleSide(self, battleSide):
        self.battleSide = battleSide

    def setMembers(self, suits, suitTraps, toons, timestamp):
        if self.battleCleanedUp():
            return

        super().setMembers(suits, suitTraps, toons, timestamp)

        # If the battle is full, we need to make the collision sphere
        # tangible so other toons can't walk through the battle
        if len(self.toons) == 4:
            self.notify.debug('setMembers() - battle is now full of toons')
            self.closeBattleCollision()
        else:
            self.openBattleCollision()

    # Each state will have an enter function, an exit function,
    # and a datagram handler, which will be set during each enter function.

    def makeSuitJoin(self, suit, *args):
        self.notify.debug('makeSuitJoin(%d)' % suit.doId)

        # We override this function from the base class to play no
        # interval.  Instead, we synchronize the animation of all of
        # the joining suits in the ReservesJoining state.
        if self.hasLocalToon():
            self.d_joinDone(suit.doId)

    def moveSuitToActivePos(self, suit, *args):
        self.notify.debug('makeSuitJoin(%d)' % suit.doId)

        # We override this function from the base class to play no
        # interval.  Instead, we synchronize the animation of all of
        # the joining suits in the ReservesJoining state.
        if self.hasLocalToon():
            self.d_joinDone(suit.doId)

    def showSuitsJoining(self, suits, ts, name, callback):
        if self.bossCog is None:
            return
        if self.battleSide:
            openDoor = Func(self.bossCog.doorB.request, 'open')
            closeDoor = Func(self.bossCog.doorB.request, 'close')
        else:
            openDoor = Func(self.bossCog.doorA.request, 'open')
            closeDoor = Func(self.bossCog.doorA.request, 'close')
        suitTrack = Parallel()
        delay = 0
        for suit in suits:
            suit: DistributedSuitBase
            suit.setState('Battle')
            suit.setPos(self.bossCog, 0, 0, 0)
            suit.headsUp(self)
            suit.setScale(3.8 / suit.height)

            # Move all suits into position
            if suit in self.joiningSuits:
                i = len(self.pendingSuits) + self.joiningSuits.index(suit)
                destPos, h = self.suitPendingPoints[i]
                destHpr = VBase3(h, 0, 0)
            else:
                destPos, destHpr = self.getActorPosHpr(suit, self.suits)
            suitTrack.append(
                Track(
                    (delay, self.createAdjustInterval(suit, destPos, destHpr)),
                    (delay + 1.5, suit.scaleInterval(1.5, 1)))
                )
            delay += 1

        suitTrack.append(self.updateActiveSuitPositions())

        done = Func(callback)
        track = Sequence(openDoor, suitTrack, closeDoor, done, name=name)
        if not self.initialReservesJoiningDone:
            camTrack = self.getCamTrack(True)
        else:
            camTrack = self.getCamTrack()
        track = Parallel(track, camTrack)
        self.initialReservesJoiningDone = True

        playRate = self.timescale
        track.start(ts, playRate=playRate)
        self.storeInterval(track, name)

    def updateActiveSuitPositions(self, suits: list=None) -> Parallel:
        suits = suits or self.activeSuits
        activeSuitTrack = Parallel()
        for suit in suits:
            # See if already in the right position
            # We might move sideways if someone died next to us
            point = self.getSuitBattlePosHpr(suit, self.suits)
            pos = suit.getPos(self)
            destPos = point[0]
            if suit.isLured:
                destPos = Point3(destPos[0], destPos[1] - MovieUtil.SUIT_LURE_DISTANCE, destPos[2])
            if pos != destPos:
                destHpr = point[1]
                adjustTime = self.calcSuitMoveTime(destPos, pos)
                activeSuitTrack.append(Sequence(
                    Func(suit.loop, 'walk'),
                    Func(suit.headsUp, self, destPos),
                    LerpPosInterval(suit, adjustTime, destPos, other=self),
                    Func(suit.setHpr, self, destHpr),
                    Func(suit.neutralAvatar)
                ))
        return activeSuitTrack

    def getCamTrack(self, override: bool=False, posHpr: tuple=None, duration: float=0.4) -> Sequence:
        if not self.hasLocalToon() or getattr(base, 'camera', None) is None:
            return Sequence()
        # Choose either a left or a right based on how close it
        # is to the current camera position.
        posHpr = posHpr or self.CAM_SUIT_JOINING_POS

        if isinstance(posHpr[0], (tuple, list)):
            def getDistance(posHpr):
                return (Vec3(*posHpr[:3]) - base.camera.getPos()).length()

            posHpr = sorted(posHpr, key=getDistance)[0]

        camPos = self.attachNewNode("camPos")
        camPos.setPosHpr(*posHpr)
        pos, hpr = camPos.getPos(base.camera.getParent()), camPos.getHpr(base.camera.getParent())
        camPos.detachNode()

        if override or base.settings["reduce-battle-effects"]:
            base.camera.wrtReparentTo(self)
            base.camLens.setMinFov(self.camFov/(4/3))
            camTrack = Sequence(
                Func(base.camera.setPosHpr, *posHpr),
            )
        else:
            camTrack = Sequence(
                LerpPosHprInterval(
                    base.camera, duration,
                    pos, hpr,
                    startPos=base.camera.getPos(), startHpr=base.camera.getHpr(),
                    blendType='easeInOut'
                ),
                Func(base.camera.wrtReparentTo, self)
            )
        return camTrack

    # Specific State functions

    ##### Off state #####

    ##### WaitForInput state #####

    ##### PlayMovie state #####

    ##### Reward state #####

    def __playReward(self, ts, callback):
        toonTracks = Parallel()
        for toon in self.toons:
            toonTracks.append(Sequence(Func(toon.loop, 'victory'), Wait(FLOOR_REWARD_TIMEOUT), Func(toon.loop, 'neutral')))

        name = self.uniqueName('floorReward')
        track = Sequence(toonTracks, name=name)
        if self.hasLocalToon():
            base.camera.setPos(0, 0, 1)
            base.camera.setHpr(180, 10, 0)
        track += [self.bossCog.makeEndOfBattleMovie(self.hasLocalToon()), Func(callback)]
        self.storeInterval(track, name)
        track.start(ts)

    def enterReward(self, ts):
        self.notify.debug('enterReward()')
        self.disableCollision()
        self.delayDeleteMembers()
        if self.hasLocalToon():
            base.cr.gameGui.expBar.show()
        self.__playReward(ts, self.__handleFloorRewardDone)

    def __handleFloorRewardDone(self):
        pass

    def exitReward(self):
        self.notify.debug('exitReward()')
        # In case the server finished first
        self.clearInterval(self.uniqueName('floorReward'), finish=1)
        self._removeMembersKeep()
        NametagGlobals.setMasterArrowsOn(1)
        for toon in self.toons:
            toon.startSmooth()

    ##### Resume state #####

    def enterResume(self, ts = 0):
        if self.hasLocalToon():
            self.removeLocalToon()

    def exitResume(self):
        pass

    ##### ReservesJoining state #####

    def enterReservesJoining(self, ts = 0):
        self.delayDeleteMembers()
        self.showSuitsJoining(self.joiningNotPendingSuits, ts, self.joiningSuitsName, self.__reservesJoiningDone)

    def __reservesJoiningDone(self):
        self._removeMembersKeep()
        self.doneBarrier()

    def exitReservesJoining(self):
        self.clearInterval(self.joiningSuitsName)

    #########################
    ##### LocalToon ClassicFSM #####
    #########################

    ##### HasLocalToon state #####

    ##### NoLocalToon state #####

    def enterNoLocalToon(self):
        self.notify.debug('enterNoLocalToon()')

        # Enable battle collision sphere, but only if localToon is
        # known to the BossCog.
        if self.bossCog is not None and self.bossCog.hasLocalToon():
            self.enableCollision()
        else:
            self.disableCollision()

    def exitNoLocalToon(self):
        # Disable battle collision sphere
        self.disableCollision()

    ##### WaitForServer state #####

    def enterWaitForServer(self):
        self.notify.debug('enterWaitForServer()')

    def exitWaitForServer(self):
        pass
