from __future__ import absolute_import
from toontown.coghq.SpecImports import *
from toontown.toonbase import ToontownGlobals
CogParent = 110400
BattleCellId = 0
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)}}
CogData = [{'type': 'autocad',
'parentEntId': CogParent,
  'boss': 0,
  'level': 16,
  'battleCell': BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
 {'type': 'clubpres',
     'parentEntId': CogParent,
  'boss': 1,
  'level': 16,
  'battleCell': BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
 {'type': 'autocad',
'parentEntId': CogParent,
  'boss': 0,
  'level': 16,
  'battleCell': BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
 {'type': 'autocad',
'parentEntId': CogParent,
  'boss': 0,
  'level': 15,
  'battleCell': BattleCellId,
  'pos': Point3(4, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
           {'type': 'autocad',
            'parentEntId': CogParent,
            'boss': 0,
            'level': 16,
            'battleCell': BattleCellId,
            'pos': Point3(-4, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': 0,
            'revives': 0},
{'type': 'autocad',
'parentEntId': CogParent,
  'boss': 0,
  'level': 15,
  'battleCell': BattleCellId,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0}
           ]
ReserveCogData = []
