from toontown.coghq.SpecImports import *
import random, sys
from toontown.toonbase import ToontownGlobals
CogParent = 10000
BattleCellId = 0
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)}}
CogData = [{'type': 'supervis',
    'parentEntId': CogParent,
  'boss': 1,
  'level': 16,
  'battleCell': BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'maudit',
     'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice((15, 16, 17)),
  'battleCell': BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'maudit',
               'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice((15, 16, 17)),
  'battleCell': BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'maudit',
               'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice((15, 16, 17)),
  'battleCell': BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0}]
ReserveCogData = []
