from __future__ import absolute_import
from toontown.coghq.SpecImports import *
from toontown.toonbase import ToontownGlobals
import random
CogParent = 10000
BattleCellId = 0
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)}}
CogData = [{'type': 'clerk',
  'parentEntId': CogParent,
  'boss': 1,
  'level': 17,
  'battleCell': BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'jdg',
            'parentEntId': CogParent,
            'boss': 0,
            'level': random.choice((16, 17, 18, 19, 20)),
  'battleCell': BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'whistleb',
            'parentEntId': CogParent,
            'boss': 0,
            'level': random.choice((16, 17, 18, 19, 20)),
  'battleCell': BattleCellId,
  'pos': Point3(-4, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
           {'type': 'whistleb',
            'parentEntId': CogParent,
            'boss': 0,
            'level': random.choice((16, 17, 18, 19, 20)),
            'battleCell': BattleCellId,
            'pos': Point3(2, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': 0},
           {'type': 'whistleb',
            'parentEntId': CogParent,
            'boss': 0,
            'level': random.choice((16, 17, 18, 19, 20)),
            'battleCell': BattleCellId,
            'pos': Point3(4, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': 0},
 {'type': 'whistleb',
            'parentEntId': CogParent,
            'boss': 0,
            'level': random.choice((16, 17, 18, 19, 20)),
  'battleCell': BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0}]
ReserveCogData = []
