from toontown.coghq.SpecImports import *
import random
from toontown.toonbase import ToontownGlobals
CogParent = 10000
BattleCellId = 0
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)}}
CogData = [{'type': 'jdg',
            'parentEntId': CogParent,
  'boss': 0,
  'level': 16,
  'battleCell': BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': random.choice(('lsc', 'arb', 'sjg', 'cfp', 'sb')),
           'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice((17, 18, 19, 20, 21, 22)),
  'battleCell': BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': random.choice(('lsc', 'arb', 'sjg', 'cfp', 'sb')),
           'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice((17, 18, 19, 20, 21, 22)),
  'battleCell': BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
           {'type': random.choice(('lsc', 'arb', 'sjg', 'cfp', 'sb')),
            'parentEntId': CogParent,
            'boss': 0,
            'level': random.choice((17, 18, 19, 20, 21, 22)),
            'battleCell': BattleCellId,
            'pos': Point3(4, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': 0},
           {'type': random.choice(('lsc', 'arb', 'sjg', 'cfp', 'sb')),
            'parentEntId': CogParent,
            'boss': 0,
            'level': random.choice((17, 18, 19, 20, 21, 22)),
            'battleCell': BattleCellId,
            'pos': Point3(-4, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': 0},
           {'type': random.choice(('lsc', 'arb', 'sjg', 'cfp', 'sb')),
            'parentEntId': CogParent,
            'boss': 0,
            'level': random.choice((17, 18, 19, 20, 21, 22)),
            'battleCell': BattleCellId,
            'pos': Point3(-4, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': 0}]
ReserveCogData = []
