from SpecImports import *
CogParent = 10000
BattleCellId = 0
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)},}
CogData = [{'type': 'ppb',
'parentEntId': CogParent,
  'boss': 1,
  'level': 1,
  'battleCell': BattleCellId,
  'pos': Point3(-40, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'shb',
'parentEntId': CogParent,
  'boss': 0,
  'level': 2,
  'battleCell': BattleCellId,
  'pos': Point3(-36, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'bsd',
'parentEntId': CogParent,
  'boss': 0,
  'level': 3,
  'battleCell': BattleCellId,
  'pos': Point3(-32, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'gms',
'parentEntId': CogParent,
  'boss': 0,
  'level': 4,
  'battleCell': BattleCellId,
  'pos': Point3(-28, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'sbg',
'parentEntId': CogParent,
  'boss': 0,
  'level': 5,
  'battleCell': BattleCellId,
  'pos': Point3(-24, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'hck',
'parentEntId': CogParent,
  'boss': 0,
  'level': 6,
  'battleCell': BattleCellId,
  'pos': Point3(-20, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'fpn',
'parentEntId': CogParent,
  'boss': 0,
  'level': 7,
  'battleCell': BattleCellId,
  'pos': Point3(-16, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'ghw',
'parentEntId': CogParent,
  'boss': 0,
  'level': 8,
  'battleCell': BattleCellId,
  'pos': Point3(-12, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'bbr',
'parentEntId': CogParent,
  'boss': 0,
  'level': 9,
  'battleCell': BattleCellId,
  'pos': Point3(-8, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'gzt',
'parentEntId': CogParent,
  'boss': 0,
  'level': 10,
  'battleCell': BattleCellId,
  'pos': Point3(-4, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'wnk',
'parentEntId': CogParent,
  'boss': 0,
  'level': 11,
  'battleCell': BattleCellId,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'nsh',
'parentEntId': CogParent,
  'boss': 0,
  'level': 12,
  'battleCell': BattleCellId,
  'pos': Point3(4, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'std',
'parentEntId': CogParent,
  'boss': 0,
  'level': 13,
  'battleCell': BattleCellId,
  'pos': Point3(8, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'anc',
'parentEntId': CogParent,
  'boss': 0,
  'level': 14,
  'battleCell': BattleCellId,
  'pos': Point3(12, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'jls',
'parentEntId': CogParent,
  'boss': 0,
  'level': 15,
  'battleCell': BattleCellId,
  'pos': Point3(16, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'pbl',
'parentEntId': CogParent,
  'boss': 0,
  'level': 16,
  'battleCell': BattleCellId,
  'pos': Point3(20, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'yuh',
'parentEntId': CogParent,
  'boss': 0,
  'level': 17,
  'battleCell': BattleCellId,
  'pos': Point3(24, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'dfg',
'parentEntId': CogParent,
  'boss': 0,
  'level': 18,
  'battleCell': BattleCellId,
  'pos': Point3(28, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'dvk',
'parentEntId': CogParent,
  'boss': 0,
  'level': 26,
  'battleCell': BattleCellId,
  'pos': Point3(32, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'otm',
'parentEntId': CogParent,
  'boss': 0,
  'level': 27,
  'battleCell': BattleCellId,
  'pos': Point3(36, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'tcm',
'parentEntId': CogParent,
  'boss': 0,
  'level': 28,
  'battleCell': BattleCellId,
  'pos': Point3(40, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'mp',
'parentEntId': CogParent,
  'boss': 0,
  'level': 23,
  'battleCell': BattleCellId,
  'pos': Point3(44, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'laa',
'parentEntId': CogParent,
  'boss': 0,
  'level': 24,
  'battleCell': BattleCellId,
  'pos': Point3(48, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'scg',
'parentEntId': CogParent,
  'boss': 0,
  'level': 25,
  'battleCell': BattleCellId,
  'pos': Point3(52, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'csm',
'parentEntId': CogParent,
  'boss': 0,
  'level': 26,
  'battleCell': BattleCellId,
  'pos': Point3(56, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'ste',
'parentEntId': CogParent,
  'boss': 0,
  'level': 27,
  'battleCell': BattleCellId,
  'pos': Point3(60, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
{'type': 'lit',
'parentEntId': CogParent,
  'boss': 0,
  'level': 28,
  'battleCell': BattleCellId,
  'pos': Point3(64, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
           ]
ReserveCogData = []