from __future__ import absolute_import
from otp.speedchat.SCStaticTextTerminal import decodeSCStaticTextMsg
from otp.speedchat.SCCustomTerminal import decodeSCCustomMsg
from otp.speedchat.SCEmoteTerminal import decodeSCEmoteWhisperMsg
