BLACKLIST = [
    'nigga',
    'niggas',
    'nigger',
    'niggers',
    'k k k',
    'kk k',
    'k kk',
    'kill your self',
    "kill you're self",
    're tart',
    're tart ed',
    're 1 tart',
    're 1 tart ed',
    'hit lure',
    'hit 1 lure',
    "'n i gg err",
    "'n i gg er",
    "'n i gg eh r",
    "jj eww",
    "jj 1 eww",
    "ought is mm",
    "aww tis mm",
    "ought 1 is mm",
    "ought 1 is 1 mm",
    "ought is 1 mm",
    "aww 1 tis mm",
    "aww 1 tis 1 mm",
    "aww tis mm",
    "aw tis mm",
    "aw 1 tis mm",
    "aw 1 tis 1 mm",
    "aw tis 1 mm",
    "awe tis mm",
    "awe 1 tis mm",
    "awe 1 tis 1 mm",
    "awe tis 1 mm",
    "kill ur self",
    "numb digger",
    "kill u r self",
    "kill you are self",
]
