"""Contains all constants relevant to toon tips."""

from enum import IntEnum, auto
from typing import Optional


class ToonTip:
    def __init__(self, canRepeat: int, showInBook: int, npcID: Optional[int], category: int):
        self.canRepeat = canRepeat
        self.showInBook = showInBook
        self.npcID = npcID
        self.category = category


class ToonTipEnum(IntEnum):
    # These don't use auto() as they are databased and need to stay constant
    NO_TIPS = 0
    TIP_LEVEL_UP = 1
    TIP_TRAINING_POINT = 2
    TIP_GAG_TRAINING = 3
    TIP_JELLYBEANS_FULL = 4
    TIP_FIRST_BATTLE = 5
    TIP_FIRST_VICTORY = 6
    TIP_EMPTY_GAGS = 7
    TIP_LURE_COG_STUN = 8
    TIP_LURE_KNOCKBACK = 9
    TIP_ZAP_NEEDS_SOAKED = 10
    TIP_COMBO_DAMAGE = 11
    TIP_EXE_COG = 12
    TIP_V2_COG = 13
    TIP_TRAP = 14
    TIP_VP_GET_PIES = 15
    TIP_VP_THROW_PIES = 16
    TIP_STUN_VP_TUTORIAL = 17
    TIP_VP_STUNNED = 18
    TIP_CFO_CRANE = 19
    TIP_CFO_SIDECRANE = 20
    TIP_CFO_STUNNED = 21
    TIP_CLO_GET_EVIDENCE = 22
    TIP_CLO_USE_EVIDENCE = 23
    TIP_CLO_EXE_DISABLING_TRAP = 24
    TIP_STUN_CLO_TUTORIAL = 25
    TIP_CLO_STUNNED = 26
    TIP_CEO_FEED_COGS = 27
    TIP_CEO_UPSET_COG = 28
    TIP_CEO_FIGHT_TUTORIAL = 29
    TIP_CEO_SELTZER = 30
    TIP_CEO_GOLF_TEES = 31
    TIP_CEO_STUNNED = 32
    TIP_ADOPT_DOODLE = 33
    TIP_UPGRADE_FISHING_ROD = 34
    TIP_FISH_BINGO = 35
    TIP_RACING = 36
    TIP_KART_SHOP = 37
    TIP_GAG_INVENTORY_INCREASE = 38
    TIP_JELLYBEAN_STORAGE_INCREASE = 39
    TIP_ACTIVITY_LEVEL_UP = 40
    TIP_TROLLEY = 41
    TIP_COG_FACILITIES = 42
    TIP_SELLBOT_DISGUISE = 43
    TIP_CASHBOT_DISGUISE = 44
    TIP_LAWBOT_DISGUISE = 45
    TIP_BOSSBOT_DISGUISE = 46
    TIP_BOARDBOT_DISGUISE = 47
    TIP_DISGUISE_PROMOTION = 48
    TIP_REWARDS_IOU = 49
    TIP_REWARDS_UNITE = 50
    TIP_REWARDS_CEASE_AND_DESIST = 51
    TIP_REWARDS_PINK_SKIP = 52
    TIP_BOARDING_GROUP = 53
    TIP_ACHIEVEMENT = 54
    TIP_DERRICK_MAN_BATTLE = 55
    TIP_FISHING = 56
    TIP_NEW_TELEPORT_ACCESS = 57
    TIP_COG_BUILDING = 58
    TIP_DERRICK_MAN_ENTRANCE = 59
    TIP_FRIENDING_COG = 60
    TIP_FIRST_RIDDLE = 61
    TIP_SECOND_RIDDLE = 62
    TIP_THIRD_RIDDLE = 63
    TIP_FINAL_RIDDLE = 64
    TIP_LURE_DECAY = 65
    TIP_LAWFICE_SKULLFINDER = 66
    TIP_LAWFICE_AVOID_SKULLS = 67
    TIP_LAWFICE_TRAPPER = 68
    TIP_LAWFICE_SIMON_SAYS = 69
    TIP_LAWFICE_DRAG_THREE = 70
    TIP_LAWFICE_MATCHING = 71
    TIP_LAWFICE_CONNECT_THREE = 72
    TIP_MAX_BATCOINS = 73
    TIP_SWEETENERS = 74
    TIP_GUMBALL_LIMIT = 75
    TIP_KUDOS_INACTIVE = 76
    TIP_KUDOS_BOARD = 77
    TIP_CONTENT_SYNC = 78
    TIP_HIGH_ROLLER_DICE = 79
    TIP_REWARDS_COUNTERFEITS = 80


# Alias for ToonTipEnum
TTE = ToonTipEnum

# Toon Tip Constants
CAN_REPEAT      = 1
CANT_REPEAT     = 0
ADD_BOOK_TIP    = 1
NO_BOOK_TIP     = 0
NO_NPC          = None
DYNAMIC_NPC     = 1

# Toon Tip Categories
CATEGORY_GEN    = 0
CATEGORY_LEVELS = 1
CATEGORY_TASKS  = 2
CATEGORY_BATTLE = 3
ToonTipCategories = (CATEGORY_GEN, CATEGORY_LEVELS, CATEGORY_TASKS, CATEGORY_BATTLE)
ToonTipTutorialSkip = [TTE.TIP_FIRST_BATTLE, TTE.TIP_FIRST_VICTORY, TTE.TIP_LURE_COG_STUN, TTE.TIP_LURE_KNOCKBACK,
                       TTE.TIP_ZAP_NEEDS_SOAKED, TTE.TIP_COMBO_DAMAGE, TTE.TIP_TRAP]
# Can repeat, add to book, npcId, category
ToonTipAttributes = {
    TTE.NO_TIPS:                        ToonTip(CANT_REPEAT, NO_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_LEVEL_UP:                   ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2003, CATEGORY_LEVELS),
    TTE.TIP_TRAINING_POINT:             ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2003, CATEGORY_LEVELS),
    TTE.TIP_GAG_TRAINING:               ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2003, CATEGORY_LEVELS),
    TTE.TIP_JELLYBEANS_FULL:            ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2003, CATEGORY_GEN),
    TTE.TIP_FIRST_BATTLE:               ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2007, CATEGORY_BATTLE),
    TTE.TIP_FIRST_VICTORY:              ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2007, CATEGORY_BATTLE),
    TTE.TIP_EMPTY_GAGS:                 ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2003, CATEGORY_GEN),
    TTE.TIP_LURE_COG_STUN:              ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2308, CATEGORY_BATTLE),
    TTE.TIP_LURE_KNOCKBACK:             ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2308, CATEGORY_BATTLE),
    TTE.TIP_ZAP_NEEDS_SOAKED:           ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 9203, CATEGORY_BATTLE),
    TTE.TIP_COMBO_DAMAGE:               ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2007, CATEGORY_BATTLE),
    TTE.TIP_EXE_COG:                    ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2007, CATEGORY_BATTLE),
    TTE.TIP_V2_COG:                     ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2010, CATEGORY_BATTLE),
    TTE.TIP_TRAP:                       ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2011, CATEGORY_BATTLE),
    TTE.TIP_VP_GET_PIES:                ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_VP_THROW_PIES:              ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_STUN_VP_TUTORIAL:           ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_VP_STUNNED:                 ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CFO_CRANE:                  ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CFO_SIDECRANE:              ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CFO_STUNNED:                ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CLO_GET_EVIDENCE:           ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CLO_USE_EVIDENCE:           ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CLO_EXE_DISABLING_TRAP:     ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_STUN_CLO_TUTORIAL:          ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CLO_STUNNED:                ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CEO_FEED_COGS:              ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CEO_UPSET_COG:              ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CEO_FIGHT_TUTORIAL:         ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CEO_SELTZER:                ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CEO_GOLF_TEES:              ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_CEO_STUNNED:                ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_ADOPT_DOODLE:               ToonTip(CANT_REPEAT, NO_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_UPGRADE_FISHING_ROD:        ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_FISH_BINGO:                 ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_RACING:                     ToonTip(CANT_REPEAT, NO_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_KART_SHOP:                  ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_GAG_INVENTORY_INCREASE:     ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2001, CATEGORY_LEVELS),
    TTE.TIP_JELLYBEAN_STORAGE_INCREASE: ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2001, CATEGORY_LEVELS),
    TTE.TIP_ACTIVITY_LEVEL_UP:          ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2001, CATEGORY_LEVELS),
    TTE.TIP_TROLLEY:                    ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2001, CATEGORY_GEN),
    TTE.TIP_COG_FACILITIES:             ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_SELLBOT_DISGUISE:           ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_CASHBOT_DISGUISE:           ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_LAWBOT_DISGUISE:            ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_BOSSBOT_DISGUISE:           ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_BOARDBOT_DISGUISE:          ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_DISGUISE_PROMOTION:         ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_REWARDS_IOU:                ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_REWARDS_UNITE:              ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_REWARDS_CEASE_AND_DESIST:   ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_REWARDS_PINK_SKIP:          ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_BOARDING_GROUP:             ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_ACHIEVEMENT:                ToonTip(CANT_REPEAT, NO_BOOK_TIP, 2003, CATEGORY_GEN),
    TTE.TIP_DERRICK_MAN_BATTLE:         ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 90001, CATEGORY_BATTLE),
    TTE.TIP_FISHING:                    ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_TASKS),
    TTE.TIP_NEW_TELEPORT_ACCESS:        ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_TASKS),
    TTE.TIP_COG_BUILDING:               ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_TASKS),
    TTE.TIP_DERRICK_MAN_ENTRANCE:       ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 2007, CATEGORY_TASKS),
    TTE.TIP_FRIENDING_COG:              ToonTip(CANT_REPEAT, ADD_BOOK_TIP, 5004, CATEGORY_TASKS),
    TTE.TIP_FIRST_RIDDLE:               ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_TASKS),
    TTE.TIP_SECOND_RIDDLE:              ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_TASKS),
    TTE.TIP_THIRD_RIDDLE:               ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_TASKS),
    TTE.TIP_FINAL_RIDDLE:               ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_TASKS),
    TTE.TIP_LURE_DECAY:                 ToonTip(CANT_REPEAT, NO_BOOK_TIP, 2308, CATEGORY_BATTLE),
    TTE.TIP_LAWFICE_SKULLFINDER:        ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_LAWFICE_AVOID_SKULLS:       ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_LAWFICE_TRAPPER:            ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_LAWFICE_SIMON_SAYS:         ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_LAWFICE_DRAG_THREE:         ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_LAWFICE_MATCHING:           ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_LAWFICE_CONNECT_THREE:      ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_MAX_BATCOINS:               ToonTip(CANT_REPEAT, NO_BOOK_TIP, NO_NPC, CATEGORY_GEN),
    TTE.TIP_SWEETENERS:                 ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_GUMBALL_LIMIT:              ToonTip(CAN_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_KUDOS_INACTIVE:             ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_TASKS),
    TTE.TIP_KUDOS_BOARD:                ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_TASKS),
    TTE.TIP_CONTENT_SYNC:               ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_HIGH_ROLLER_DICE:           ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
    TTE.TIP_REWARDS_COUNTERFEITS:       ToonTip(CANT_REPEAT, ADD_BOOK_TIP, NO_NPC, CATEGORY_BATTLE),
}
