HIGH_ROLLER = 'highRoller'
VIDEOGRAPHER = 'videographer'
PACESETTER = 'pacesetter'
CHAINSAW = 'chainsaw'

INSTANCE_HIGH_ROLLER = HIGH_ROLLER
INSTANCE_VIDEOGRAPHER = VIDEOGRAPHER
INSTANCE_PACESETTER = PACESETTER
INSTANCE_CHAINSAW = CHAINSAW
