HIGH_ROLLER = 'highRoller'
VIDEOGRAPHER = 'videographer'
PACESETTER = 'pacesetter'
CHAINSAW = 'chainsaw'
MOTOROOM = 'motoroom'
PLUTOCRAT = 'plutocrat'
COUNT_ERFIT = 'countErfit'

# Boss Types
DERRICK_MAN = 0
LAND_ACQUISITION = 1
YOTT_DUNGEON = 2
DIRECTORS = 3
COUNT_ERCLAIM = 4
COUNT_ERFIT = 5
INSTANCE_MERC = 6

INSTANCE_HIGH_ROLLER = HIGH_ROLLER
INSTANCE_VIDEOGRAPHER = VIDEOGRAPHER
INSTANCE_PACESETTER = PACESETTER
INSTANCE_CHAINSAW = CHAINSAW
INSTANCE_MOTOROOM = MOTOROOM
INSTANCE_PLUTOCRAT = PLUTOCRAT
INSTANCE_COUNT_ERFIT = COUNT_ERFIT
