NET_MESSENGER_REGISTER_SHARD = 'registerShard'

NET_MESSENGER_REQUEST_DRAINING_DISTRICT_REQUEST = 'requestDrainingDistrictRequest'
NET_MESSENGER_REQUEST_DRAINING_DISTRICT_RESPONSE = 'requestDrainingDistrictResponse'

NET_MESSENGER_DISTRICT_STATUS_REQUEST = 'requestDistrictStatus'
NET_MESSENGER_DISTRICT_STATUS = 'districtStatus'

NET_MESSENGER_SHARD_INVASION_STATUS = 'shardInvasionStatus'

NET_MESSENGER_REQUEST_SPAWNING_SHARD = 'requestSpawningShard'
NET_MESSENGER_REQUEST_SPAWNING_SHARD_RESPONSE = 'requestSpawningShardResponse'

MESSENGER_SHARD_ONLINE = 'MESSENGER_SHARD_ONLINE'  # [airChannel, shardId]
MESSENGER_SHARD_OFFLINE = 'MESSENGER_SHARD_OFFLINE'  # [airChannel, shardId]
MESSENGER_SHARD_ALIVE = 'MESSENGER_SHARD_ALIVE'  # [airChannel, stats]
