from direct.particles.ParticleEffect import ParticleEffect
from panda3d.core import *
from panda3d.physics import *
from direct.particles import Particles


def chillyAir(self):
    self.reset()
    self.setPos(0, 0, 0)
    self.setHpr(0, 0, 0)
    self.setScale(1, 1, 1)
    p0 = Particles.Particles('particles-1')
    p0.setFactory('ZSpinParticleFactory')
    p0.setRenderer('SpriteParticleRenderer')
    p0.setEmitter('DiscEmitter')
    p0.setPoolSize(100)
    p0.setBirthRate(0.0750)
    p0.setLitterSize(3)
    p0.setLitterSpread(1)
    p0.setSystemLifespan(0.0)
    p0.setLocalVelocityFlag(1)
    p0.setSystemGrowsOlderFlag(0)
    p0.factory.setLifespanBase(1.5)
    p0.factory.setLifespanSpread(1.0)
    p0.factory.setMassBase(1.0)
    p0.factory.setMassSpread(0.0)
    p0.factory.setTerminalVelocityBase(400.0)
    p0.factory.setTerminalVelocitySpread(0.0)
    p0.factory.setInitialAngle(0.0)
    p0.factory.setInitialAngleSpread(360.0)
    p0.factory.enableAngularVelocity(1)
    p0.factory.setAngularVelocity(0.0)
    p0.factory.setAngularVelocitySpread(0.0)
    p0.renderer.setAlphaMode(BaseParticleRenderer.PRALPHAINOUT)
    p0.renderer.setUserAlpha(0.20)
    p0.renderer.setTexture(loader.loadTexture('phase_3.5/maps/splash_particle.png'))
    p0.renderer.setColor(Vec4(1, 1, 1, 0.20))
    p0.renderer.setXScaleFlag(0)
    p0.renderer.setYScaleFlag(0)
    p0.renderer.setAnimAngleFlag(1)
    p0.renderer.setInitialXScale(0.2)
    p0.renderer.setFinalXScale(0.0)
    p0.renderer.setInitialYScale(0.2)
    p0.renderer.setFinalYScale(0.0)
    p0.renderer.setNonanimatedTheta(0.0)
    p0.renderer.setAlphaBlendMethod(BaseParticleRenderer.PP_BLEND_CUBIC)
    p0.renderer.setAlphaDisable(0)
    p0.renderer.setColorBlendMode(ColorBlendAttrib.MAdd, ColorBlendAttrib.OIncomingAlpha, ColorBlendAttrib.OOne)
    p0.emitter.setEmissionType(BaseParticleEmitter.ETRADIATE)
    p0.emitter.setAmplitude(5.0)
    p0.emitter.setAmplitudeSpread(1.0)
    p0.emitter.setOffsetForce(Vec3(0, 0, -40))
    p0.emitter.setExplicitLaunchVector(Vec3(0, 0, 0))
    p0.emitter.setRadiateOrigin(Point3(0, 0, 0))
    p0.emitter.setRadius(20.0)
    self.addParticles(p0)


def chillyFlakes(self):
    self.reset()
    self.setPos(0, 0, 0)
    self.setHpr(0, 0, 0)
    self.setScale(1, 1, 1)
    p0 = Particles.Particles('particles-1')
    p0.setFactory('ZSpinParticleFactory')
    p0.setRenderer('SpriteParticleRenderer')
    p0.setEmitter('DiscEmitter')
    p0.setPoolSize(100)
    p0.setBirthRate(0.0750)
    p0.setLitterSize(3)
    p0.setLitterSpread(1)
    p0.setSystemLifespan(0.0)
    p0.setLocalVelocityFlag(1)
    p0.setSystemGrowsOlderFlag(0)
    p0.factory.setLifespanBase(1.5)
    p0.factory.setLifespanSpread(0.0)
    p0.factory.setMassBase(1.0)
    p0.factory.setMassSpread(0.0)
    p0.factory.setTerminalVelocityBase(400.0)
    p0.factory.setTerminalVelocitySpread(0.0)
    p0.factory.setInitialAngle(0.0)
    p0.factory.setInitialAngleSpread(360.0)
    p0.factory.enableAngularVelocity(0)
    p0.factory.setFinalAngle(0.0)
    p0.factory.setFinalAngleSpread(0.0)
    p0.renderer.setAlphaMode(BaseParticleRenderer.PRALPHAINOUT)
    p0.renderer.setUserAlpha(1.0)
    p0.renderer.setTextureFromNode('phase_3.5/models/props/suit-particles', '**/snow-particle')
    p0.renderer.setColor(Vec4(1, 1, 1, 1))
    p0.renderer.setXScaleFlag(1)
    p0.renderer.setYScaleFlag(1)
    p0.renderer.setAnimAngleFlag(1)
    p0.renderer.setInitialXScale(1.0)
    p0.renderer.setFinalXScale(0.0)
    p0.renderer.setInitialYScale(1.0)
    p0.renderer.setFinalYScale(0.0)
    p0.renderer.setNonanimatedTheta(0.0)
    p0.renderer.setAlphaBlendMethod(BaseParticleRenderer.PPBLENDLINEAR)
    p0.renderer.setColorBlendMode(ColorBlendAttrib.MAdd, ColorBlendAttrib.OIncomingAlpha, ColorBlendAttrib.OOne)
    p0.renderer.setAlphaDisable(0)
    p0.emitter.setEmissionType(BaseParticleEmitter.ETRADIATE)
    p0.emitter.setAmplitude(8.0)
    p0.emitter.setAmplitudeSpread(1.0)
    p0.emitter.setOffsetForce(Vec3(0, 0, -40))
    p0.emitter.setExplicitLaunchVector(Vec3(0, 0, 0))
    p0.emitter.setRadiateOrigin(Point3(0, 0, 0))
    p0.emitter.setRadius(20.0)
    self.addParticles(p0)


FACTORIES = {'chillyAir': chillyAir, 'chillyFlakes': chillyFlakes}


def getPlutocratParticle(name):
    effect = ParticleEffect()
    FACTORIES[name](effect)
    return effect


def getPlutocratParticles(names):
    return [getPlutocratParticle(name) for name in names]
